<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="TA110" targetNamespace="http://tempuri.org/TA110.xsd" elementFormDefault="qualified"
  xmlns="http://tempuri.org/TA110.xsd" xmlns:mstns="http://tempuri.org/TA110.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="TXOWN">
<xs:complexType>
<xs:sequence>
<xs:element name="oid" type="xs:string" />
<xs:element name="name" type="xs:string" />
<xs:element name="sname" type="xs:string" />
<xs:element name="add1" type="xs:string" />
<xs:element name="add2" type="xs:string" />
<xs:element name="city" type="xs:string" />
<xs:element name="state" type="xs:string" />
<xs:element name="zip5" type="xs:integer" />
<xs:element name="zip4" type="xs:integer" />
<xs:element name="ss" type="xs:integer" />
<xs:element name="ss2" type="xs:integer" />
<xs:element name="tin" type="xs:string" />
<xs:element name="tel" type="xs:integer" />
<xs:element name="dob" type="xs:integer" />
<xs:element name="comt" type="xs:string" />
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>