<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="TA520" targetNamespace="http://tempuri.org/TA520.xsd" elementFormDefault="qualified"
  xmlns="http://tempuri.org/TA520.xsd" xmlns:mstns="http://tempuri.org/TA520.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="mytable">
<xs:complexType>
<xs:sequence>
<xs:element name="SORT" type="xs:string" />
<xs:element name="LISTNO" type="xs:integer" />
<xs:element name="ADDR1" type="xs:string" />
<xs:element name="ADDR2" type="xs:string" />
<xs:element name="ADDR3" type="xs:string" />
<xs:element name="ADDR4" type="xs:string" />
<xs:element name="ADDR5" type="xs:string" />
<xs:element name="MAKE" type="xs:string" />
<xs:element name="MODEL" type="xs:string" />
<xs:element name="YEAR" type="xs:integer" />
<xs:element name="REGNO" type="xs:string" />
<xs:element name="CLASS" type="xs:integer" />
<xs:element name="VINNO" type="xs:string" />
<xs:element name="PCLR" type="xs:string" />
<xs:element name="LWT" type="xs:integer" />
<xs:element name="VALUE" type="xs:integer" />
<xs:element name="SCAP" type="xs:integer" />
<xs:element name="SCLR" type="xs:string" />
<xs:element name="GWT" type="xs:integer" />
<xs:element name="ASS" type="xs:string" />
<xs:element name="OMAKE" type="xs:string" />
<xs:element name="OMOD" type="xs:string" />
<xs:element name="OYEAR" type="xs:integer" />
<xs:element name="OREGNO" type="xs:string" />
<xs:element name="OCLS" type="xs:integer" />
<xs:element name="OVIN" type="xs:string" />
<xs:element name="OVAL" type="xs:integer" />
<xs:element name="OASS" type="xs:string" />
<xs:element name="PCUSTID" type="xs:integer" />
<xs:element name="SCUSTID" type="xs:integer" />
<xs:element name="VEHID" type="xs:integer" />
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>
