<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="TXA04" targetNamespace="http://tempuri.org/TXA04.xsd" elementFormDefault="qualified" xmlns="http://tempuri.org/TXA04.xsd" xmlns:mstns="http://tempuri.org/TXA04.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="mytable">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="COUNT" type="xs:integer" />
				<xs:element name="BANKCD" type="xs:string" />
				<xs:element name="BANKNAME" type="xs:string" />
				<xs:element name="CHECKNO" type="xs:string" />
				<xs:element name="PAMT" type="xs:decimal" />
				<xs:element name="IAMT" type="xs:decimal" />
				<xs:element name="PCAMT" type="xs:decimal" />
        <xs:element name="LAMT" type="xs:decimal" />
        <xs:element name="TOTAL" type="xs:decimal" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>