<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="UB102" targetNamespace="http://tempuri.org/UB102.xsd" elementFormDefault="qualified"
  xmlns="http://tempuri.org/UB102.xsd" xmlns:mstns="http://tempuri.org/UB102.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="mytable">
<xs:complexType>
<xs:sequence>
<xs:element name="LISTNO" type="xs:integer" />
<xs:element name="BILLTYPE" type="xs:string" />
<xs:element name="ADDR1" type="xs:string" />
<xs:element name="ADDR2" type="xs:string" />
<xs:element name="ADDR3" type="xs:string" />
<xs:element name="ADDR4" type="xs:string" />
<xs:element name="ADDR5" type="xs:string" />
<xs:element name="LOCATION" type="xs:string" />
<xs:element name="UNITS" type="xs:decimal" />
<xs:element name="ORIGASSMNT" type="xs:decimal" />
<xs:element name="DEFERRED" type="xs:decimal" />
<xs:element name="BONDPCT" type="xs:decimal" />
</xs:sequence>
</xs:complexType>
<xs:key name="mytableKey1">
<xs:selector xpath="." />
<xs:field xpath="mstns:LISTNO" />
</xs:key>
</xs:element>
<xs:element name="mytable2">
<xs:complexType>
<xs:sequence>
<xs:element name="LISTNO" type="xs:integer" />
<xs:element name="PAYMENTNO" type="xs:integer" />
<xs:element name="BILLAMT" type="xs:decimal" />
<xs:element name="PRINCIPAL" type="xs:decimal" />
<xs:element name="BOND" type="xs:decimal" />
<xs:element name="BALANCE" type="xs:decimal" />
</xs:sequence>
</xs:complexType>
<xs:keyref name="Join1" refer="mytableKey1">
<xs:selector xpath="." />
<xs:field xpath="mstns:LISTNO" />
</xs:keyref>
</xs:element>
</xs:schema>