<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="TA941" targetNamespace="http://tempuri.org/TA941.xsd" elementFormDefault="qualified" xmlns="http://tempuri.org/TA941.xsd" xmlns:mstns="http://tempuri.org/TA941.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="mytable">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="SORTDATA" type="xs:integer" />
        <xs:element name="LISTNO" type="xs:integer" />
        <xs:element name="NAME" type="xs:string" />
        <xs:element name="MSRP" type="xs:integer" />
        <xs:element name="VALUE" type="xs:integer" />
        <xs:element name="NVALUE" type="xs:integer" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>