<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="TO112" targetNamespace="http://tempuri.org/TO112.xsd" elementFormDefault="qualified" xmlns="http://tempuri.org/TO112.xsd" xmlns:mstns="http://tempuri.org/TO112.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="mytable">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="LISTNO" type="xs:integer" />
        <xs:element name="NAME" type="xs:string" />
        <xs:element name="PROPLOC" type="xs:string" />
        <xs:element name="UNITS" type="xs:integer" />
        <xs:element name="GROSS" type="xs:integer" />
        <xs:element name="TAX" type="xs:decimal" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>