<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="TXE25" targetNamespace="http://tempuri.org/TXE25.xsd" elementFormDefault="qualified"
  xmlns="http://tempuri.org/TXE25.xsd" xmlns:mstns="http://tempuri.org/TXE25.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="mytable">
<xs:complexType>
<xs:sequence>
  <xs:element name="LISTNO" type="xs:integer" />
  <xs:element name="YEAR" type="xs:integer" />
  <xs:element name="TYPE" type="xs:string" />
  <xs:element name="ADDR1" type="xs:string" />
  <xs:element name="ADDR2" type="xs:string" />
  <xs:element name="ADDR3" type="xs:string" />
  <xs:element name="ADDR4" type="xs:string" />
  <xs:element name="ADDR5" type="xs:string" />
  <xs:element name="MAP" type="xs:string" />
  <xs:element name="NADDR1" type="xs:string" />
  <xs:element name="NADDR2" type="xs:string" />
  <xs:element name="NADDR3" type="xs:string" />
  <xs:element name="NADDR4" type="xs:string" />
  <xs:element name="NADDR5" type="xs:string" />
  <xs:element name="NMAP" type="xs:string" />
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>