<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="TXE51Tot" targetNamespace="http://tempuri.org/TXE51Tot.xsd" elementFormDefault="qualified"
  xmlns="http://tempuri.org/TXE51Tot.xsd" xmlns:mstns="http://tempuri.org/TXE51Tot.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="mytable2">
<xs:complexType>
<xs:sequence>
<xs:element name="YEAR" type="xs:integer" />
<xs:element name="TYPE" type="xs:string" />
<xs:element name="TCOUNT" type="xs:integer" />
<xs:element name="TPRINPAID" type="xs:double" />
<xs:element name="TBRKAMT1" type="xs:decimal" />
<xs:element name="TBRKAMT2" type="xs:decimal" />
<xs:element name="TBRKAMT3" type="xs:decimal" />
<xs:element name="TBRKAMT4" type="xs:decimal" />
<xs:element name="TBRKAMT5" type="xs:decimal" />
<xs:element name="TBRKAMT6" type="xs:decimal" />
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>