SET PATH=%PATH%;C:\gemssql;
digicertutil sign /noinput c:\gemssql\ap101.exe
digicertutil sign /noinput c:\gemssql\ap103.exe
digicertutil sign /noinput c:\gemssql\ap201.exe
digicertutil sign /noinput c:\gemssql\ap202.exe
digicertutil sign /noinput c:\gemssql\ap230.exe
digicertutil sign /noinput c:\gemssql\ap231.exe
digicertutil sign /noinput c:\gemssql\ap304.exe
digicertutil sign /noinput c:\gemssql\ap305.exe
digicertutil sign /noinput c:\gemssql\ap307.exe
digicertutil sign /noinput c:\gemssql\ap311.exe
digicertutil sign /noinput c:\gemssql\ap312.exe
digicertutil sign /noinput c:\gemssql\ap313.exe
digicertutil sign /noinput c:\gemssql\ap330.exe
digicertutil sign /noinput c:\gemssql\ap401.exe
digicertutil sign /noinput c:\gemssql\ap403.exe
digicertutil sign /noinput c:\gemssql\ap404.exe
digicertutil sign /noinput c:\gemssql\ap405.exe
digicertutil sign /noinput c:\gemssql\ap502.exe
digicertutil sign /noinput c:\gemssql\ap504.exe
digicertutil sign /noinput c:\gemssql\ap510.exe
digicertutil sign /noinput c:\gemssql\ap530.exe
digicertutil sign /noinput c:\gemssql\ap600.exe
digicertutil sign /noinput c:\gemssql\ap602.exe
digicertutil sign /noinput c:\gemssql\ap701.exe
digicertutil sign /noinput c:\gemssql\ap702.exe
digicertutil sign /noinput c:\gemssql\ap703.exe
digicertutil sign /noinput c:\gemssql\ap706.exe
digicertutil sign /noinput c:\gemssql\ap730.exe
