SET PATH=%PATH%;C:\gemssql;
digicertutil sign /noinput c:\gemssql\fa001.exe
digicertutil sign /noinput c:\gemssql\fa002.exe
digicertutil sign /noinput c:\gemssql\fa003.exe
digicertutil sign /noinput c:\gemssql\fa004.exe
digicertutil sign /noinput c:\gemssql\fa005.exe
digicertutil sign /noinput c:\gemssql\fa006.exe
digicertutil sign /noinput c:\gemssql\fa007.exe
digicertutil sign /noinput c:\gemssql\fa008.exe
digicertutil sign /noinput c:\gemssql\fa009.exe
digicertutil sign /noinput c:\gemssql\fa010.exe
digicertutil sign /noinput c:\gemssql\fa011.exe
digicertutil sign /noinput c:\gemssql\fa012.exe
digicertutil sign /noinput c:\gemssql\fa020.exe
digicertutil sign /noinput c:\gemssql\fa100.exe
digicertutil sign /noinput c:\gemssql\fa101.exe
digicertutil sign /noinput c:\gemssql\fa102.exe
digicertutil sign /noinput c:\gemssql\fa103.exe
digicertutil sign /noinput c:\gemssql\fa104.exe
digicertutil sign /noinput c:\gemssql\fa200.exe
