SET PATH=%PATH%;C:\gemssql;
digicertutil sign /noinput c:\gemssql\gl101.exe
digicertutil sign /noinput c:\gemssql\gl102.exe
digicertutil sign /noinput c:\gemssql\gl103.exe
digicertutil sign /noinput c:\gemssql\gl104.exe
digicertutil sign /noinput c:\gemssql\gl105.exe
digicertutil sign /noinput c:\gemssql\gl107.exe
digicertutil sign /noinput c:\gemssql\gl111.exe
digicertutil sign /noinput c:\gemssql\gl114.exe
digicertutil sign /noinput c:\gemssql\gl205.exe
digicertutil sign /noinput c:\gemssql\gl212.exe
digicertutil sign /noinput c:\gemssql\gl214.exe
digicertutil sign /noinput c:\gemssql\gl216.exe
digicertutil sign /noinput c:\gemssql\gl220.exe
digicertutil sign /noinput c:\gemssql\gl244.exe
digicertutil sign /noinput c:\gemssql\gl401.exe
digicertutil sign /noinput c:\gemssql\gl402.exe
digicertutil sign /noinput c:\gemssql\gl403.exe
digicertutil sign /noinput c:\gemssql\gl501.exe
digicertutil sign /noinput c:\gemssql\gl502.exe
digicertutil sign /noinput c:\gemssql\gl503.exe
digicertutil sign /noinput c:\gemssql\gl505.exe
digicertutil sign /noinput c:\gemssql\gl506.exe
digicertutil sign /noinput c:\gemssql\gl509.exe
digicertutil sign /noinput c:\gemssql\gl510.exe
digicertutil sign /noinput c:\gemssql\gl520.exe
digicertutil sign /noinput c:\gemssql\gl530.exe
digicertutil sign /noinput c:\gemssql\gl531.exe
digicertutil sign /noinput c:\gemssql\gl600.exe
digicertutil sign /noinput c:\gemssql\gl650.exe
digicertutil sign /noinput c:\gemssql\gl651.exe
digicertutil sign /noinput c:\gemssql\gl652.exe
digicertutil sign /noinput c:\gemssql\gl660.exe
digicertutil sign /noinput c:\gemssql\gl661.exe
digicertutil sign /noinput c:\gemssql\gl701.exe
digicertutil sign /noinput c:\gemssql\gl703.exe
digicertutil sign /noinput c:\gemssql\gl704.exe
digicertutil sign /noinput c:\gemssql\gl730.exe
digicertutil sign /noinput c:\gemssql\gl801.exe
digicertutil sign /noinput c:\gemssql\gl802.exe
digicertutil sign /noinput c:\gemssql\gla01.exe
digicertutil sign /noinput c:\gemssql\gla02.exe
digicertutil sign /noinput c:\gemssql\gla31.exe
digicertutil sign /noinput c:\gemssql\gla32.exe
digicertutil sign /noinput c:\gemssql\gla33.exe
digicertutil sign /noinput c:\gemssql\gla34.exe
digicertutil sign /noinput c:\gemssql\gla35.exe
digicertutil sign /noinput c:\gemssql\gla36.exe
digicertutil sign /noinput c:\gemssql\gla37.exe
digicertutil sign /noinput c:\gemssql\gla40.exe
digicertutil sign /noinput c:\gemssql\gla41.exe
digicertutil sign /noinput c:\gemssql\gla42.exe
digicertutil sign /noinput c:\gemssql\gla43.exe
digicertutil sign /noinput c:\gemssql\gla44.exe
digicertutil sign /noinput c:\gemssql\gla45.exe
digicertutil sign /noinput c:\gemssql\gla46.exe
