SET PATH=%PATH%;C:\Program Files (x86)\CrSSL\bin;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Azure Data Studio\bin;%USERPROFILE%\.dotnet\tools;C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\amd64;
msbuild.exe "c:\gems source sql\pk source\pk100\pk100.sln" /property:configuration=release
msbuild.exe "c:\gems source sql\pk source\pk110\pk110.sln" /property:configuration=release
msbuild.exe "c:\gems source sql\pk source\pk111\pk111.sln" /property:configuration=release
msbuild.exe "c:\gems source sql\pk source\pk112\pk112.sln" /property:configuration=release
msbuild.exe "c:\gems source sql\pk source\pk120\pk120.sln" /property:configuration=release
msbuild.exe "c:\gems source sql\pk source\pk200\pk200.sln" /property:configuration=release
msbuild.exe "c:\gems source sql\pk source\pk220\pk220.sln" /property:configuration=release
msbuild.exe "c:\gems source sql\pk source\pk230\pk230.sln" /property:configuration=release
