SET PATH=%PATH%;C:\gemssql;
digicertutil sign /noinput c:\gemssql\ta001.exe
digicertutil sign /noinput c:\gemssql\ta101.exe
digicertutil sign /noinput c:\gemssql\ta102.exe
digicertutil sign /noinput c:\gemssql\ta103.exe
digicertutil sign /noinput c:\gemssql\ta104.exe
digicertutil sign /noinput c:\gemssql\ta105.exe
digicertutil sign /noinput c:\gemssql\ta106.exe
digicertutil sign /noinput c:\gemssql\ta107.exe
digicertutil sign /noinput c:\gemssql\ta108.exe
digicertutil sign /noinput c:\gemssql\ta109.exe
digicertutil sign /noinput c:\gemssql\ta110.exe
digicertutil sign /noinput c:\gemssql\ta111.exe
digicertutil sign /noinput c:\gemssql\ta130.exe
digicertutil sign /noinput c:\gemssql\ta131.exe
digicertutil sign /noinput c:\gemssql\ta132.exe
digicertutil sign /noinput c:\gemssql\ta133.exe
digicertutil sign /noinput c:\gemssql\ta134.exe
digicertutil sign /noinput c:\gemssql\ta135.exe
digicertutil sign /noinput c:\gemssql\ta136.exe
digicertutil sign /noinput c:\gemssql\ta137.exe
digicertutil sign /noinput c:\gemssql\ta138.exe
digicertutil sign /noinput c:\gemssql\ta202.exe
digicertutil sign /noinput c:\gemssql\ta203.exe
digicertutil sign /noinput c:\gemssql\ta204.exe
digicertutil sign /noinput c:\gemssql\ta205.exe
digicertutil sign /noinput c:\gemssql\ta206.exe
digicertutil sign /noinput c:\gemssql\ta207.exe
digicertutil sign /noinput c:\gemssql\ta208.exe
digicertutil sign /noinput c:\gemssql\ta209.exe
digicertutil sign /noinput c:\gemssql\ta212.exe
digicertutil sign /noinput c:\gemssql\ta213.exe
digicertutil sign /noinput c:\gemssql\ta215.exe
digicertutil sign /noinput c:\gemssql\ta216.exe
digicertutil sign /noinput c:\gemssql\ta217.exe
digicertutil sign /noinput c:\gemssql\ta218.exe
digicertutil sign /noinput c:\gemssql\ta219.exe
digicertutil sign /noinput c:\gemssql\ta220.exe
digicertutil sign /noinput c:\gemssql\ta221.exe
digicertutil sign /noinput c:\gemssql\ta222.exe
digicertutil sign /noinput c:\gemssql\ta226.exe
digicertutil sign /noinput c:\gemssql\ta230.exe
digicertutil sign /noinput c:\gemssql\ta231.exe
digicertutil sign /noinput c:\gemssql\ta232.exe
digicertutil sign /noinput c:\gemssql\ta233.exe
digicertutil sign /noinput c:\gemssql\ta234.exe
digicertutil sign /noinput c:\gemssql\ta235.exe
digicertutil sign /noinput c:\gemssql\ta236.exe
digicertutil sign /noinput c:\gemssql\ta237.exe
digicertutil sign /noinput c:\gemssql\ta238.exe
digicertutil sign /noinput c:\gemssql\ta304.exe
digicertutil sign /noinput c:\gemssql\ta314.exe
digicertutil sign /noinput c:\gemssql\ta316.exe
digicertutil sign /noinput c:\gemssql\ta330.exe
digicertutil sign /noinput c:\gemssql\ta331.exe
digicertutil sign /noinput c:\gemssql\ta402.exe
digicertutil sign /noinput c:\gemssql\ta403.exe
digicertutil sign /noinput c:\gemssql\ta404.exe
digicertutil sign /noinput c:\gemssql\ta406.exe
