SET PATH=%PATH%;C:\gemssql;
digicertutil sign /noinput c:\gemssql\ta4071.exe
digicertutil sign /noinput c:\gemssql\ta4072.exe
digicertutil sign /noinput c:\gemssql\ta4073.exe
digicertutil sign /noinput c:\gemssql\ta4074.exe
digicertutil sign /noinput c:\gemssql\ta4075.exe
digicertutil sign /noinput c:\gemssql\ta4076.exe
digicertutil sign /noinput c:\gemssql\ta4077.exe
digicertutil sign /noinput c:\gemssql\ta408.exe
digicertutil sign /noinput c:\gemssql\ta413.exe
digicertutil sign /noinput c:\gemssql\ta414.exe
digicertutil sign /noinput c:\gemssql\ta420.exe
digicertutil sign /noinput c:\gemssql\ta421.exe
digicertutil sign /noinput c:\gemssql\ta423.exe
digicertutil sign /noinput c:\gemssql\ta430.exe
digicertutil sign /noinput c:\gemssql\ta431.exe
digicertutil sign /noinput c:\gemssql\ta502.exe
digicertutil sign /noinput c:\gemssql\ta503.exe
digicertutil sign /noinput c:\gemssql\ta504.exe
digicertutil sign /noinput c:\gemssql\ta506.exe
digicertutil sign /noinput c:\gemssql\ta5071.exe
digicertutil sign /noinput c:\gemssql\ta5072.exe
digicertutil sign /noinput c:\gemssql\ta5073.exe
digicertutil sign /noinput c:\gemssql\ta5074.exe
digicertutil sign /noinput c:\gemssql\ta5075.exe
digicertutil sign /noinput c:\gemssql\ta5076.exe
digicertutil sign /noinput c:\gemssql\ta5077.exe
digicertutil sign /noinput c:\gemssql\ta5078.exe
digicertutil sign /noinput c:\gemssql\ta509.exe
digicertutil sign /noinput c:\gemssql\ta513.exe
digicertutil sign /noinput c:\gemssql\ta514.exe
digicertutil sign /noinput c:\gemssql\ta518.exe
digicertutil sign /noinput c:\gemssql\ta519.exe
digicertutil sign /noinput c:\gemssql\ta520.exe
digicertutil sign /noinput c:\gemssql\ta521.exe
digicertutil sign /noinput c:\gemssql\ta523.exe
digicertutil sign /noinput c:\gemssql\ta524.exe
digicertutil sign /noinput c:\gemssql\ta525.exe
digicertutil sign /noinput c:\gemssql\ta530.exe
digicertutil sign /noinput c:\gemssql\ta531.exe
digicertutil sign /noinput c:\gemssql\ta600.exe
digicertutil sign /noinput c:\gemssql\ta801.exe
digicertutil sign /noinput c:\gemssql\ta810.exe
digicertutil sign /noinput c:\gemssql\ta811.exe
digicertutil sign /noinput c:\gemssql\ta901.exe
digicertutil sign /noinput c:\gemssql\ta902.exe
digicertutil sign /noinput c:\gemssql\ta903.exe
digicertutil sign /noinput c:\gemssql\ta904.exe
digicertutil sign /noinput c:\gemssql\ta940.exe
digicertutil sign /noinput c:\gemssql\ta941.exe
digicertutil sign /noinput c:\gemssql\ta942.exe
digicertutil sign /noinput c:\gemssql\tab01.exe
digicertutil sign /noinput c:\gemssql\tab02.exe
digicertutil sign /noinput c:\gemssql\tab03.exe
digicertutil sign /noinput c:\gemssql\tab04.exe
digicertutil sign /noinput c:\gemssql\tac01.exe
digicertutil sign /noinput c:\gemssql\tad01.exe
digicertutil sign /noinput c:\gemssql\tad02.exe
digicertutil sign /noinput c:\gemssql\tad03.exe
digicertutil sign /noinput c:\gemssql\tad04.exe
digicertutil sign /noinput c:\gemssql\tad05.exe
digicertutil sign /noinput c:\gemssql\tae01.exe
digicertutil sign /noinput c:\gemssql\tae02.exe
digicertutil sign /noinput c:\gemssql\tap01.exe
digicertutil sign /noinput c:\gemssql\tap02.exe
digicertutil sign /noinput c:\gemssql\tap03.exe
digicertutil sign /noinput c:\gemssql\tap10.exe
digicertutil sign /noinput c:\gemssql\tap11.exe
digicertutil sign /noinput c:\gemssql\tap12.exe
digicertutil sign /noinput c:\gemssql\tap13.exe
digicertutil sign /noinput c:\gemssql\tap14.exe
digicertutil sign /noinput c:\gemssql\tap15.exe
digicertutil sign /noinput c:\gemssql\tap16.exe
digicertutil sign /noinput c:\gemssql\tap17.exe
digicertutil sign /noinput c:\gemssql\tap20.exe
digicertutil sign /noinput c:\gemssql\tap21.exe
digicertutil sign /noinput c:\gemssql\tap22.exe
digicertutil sign /noinput c:\gemssql\tap23.exe
digicertutil sign /noinput c:\gemssql\tap24.exe
