SET PATH=%PATH%;C:\gemssql;
digicertutil sign /noinput c:\gemssql\to101.exe
digicertutil sign /noinput c:\gemssql\to102.exe
digicertutil sign /noinput c:\gemssql\to103.exe
digicertutil sign /noinput c:\gemssql\to104.exe
digicertutil sign /noinput c:\gemssql\to105.exe
digicertutil sign /noinput c:\gemssql\to106.exe
digicertutil sign /noinput c:\gemssql\to107.exe
digicertutil sign /noinput c:\gemssql\to109.exe
digicertutil sign /noinput c:\gemssql\to110.exe
digicertutil sign /noinput c:\gemssql\to111.exe
digicertutil sign /noinput c:\gemssql\to112.exe
digicertutil sign /noinput c:\gemssql\to113.exe
digicertutil sign /noinput c:\gemssql\to114.exe
digicertutil sign /noinput c:\gemssql\to116.exe
digicertutil sign /noinput c:\gemssql\to120.exe
digicertutil sign /noinput c:\gemssql\to200.exe
digicertutil sign /noinput c:\gemssql\to201.exe
digicertutil sign /noinput c:\gemssql\to202.exe
digicertutil sign /noinput c:\gemssql\to203.exe
digicertutil sign /noinput c:\gemssql\to204.exe
digicertutil sign /noinput c:\gemssql\to205.exe
digicertutil sign /noinput c:\gemssql\to206.exe
digicertutil sign /noinput c:\gemssql\to207.exe
digicertutil sign /noinput c:\gemssql\to208.exe
digicertutil sign /noinput c:\gemssql\to300.exe
digicertutil sign /noinput c:\gemssql\to301.exe
