SET PATH=%PATH%;C:\gemssql;
digicertutil sign /noinput c:\gemssql\cashasof.exe
digicertutil sign /noinput c:\gemssql\cashint.exe
digicertutil sign /noinput c:\gemssql\tpaymnt.exe
digicertutil sign /noinput c:\gemssql\tx101.exe
digicertutil sign /noinput c:\gemssql\tx102.exe
digicertutil sign /noinput c:\gemssql\tx103.exe
digicertutil sign /noinput c:\gemssql\tx104.exe
digicertutil sign /noinput c:\gemssql\tx105.exe
digicertutil sign /noinput c:\gemssql\tx106.exe
digicertutil sign /noinput c:\gemssql\tx107.exe
digicertutil sign /noinput c:\gemssql\tx108.exe
digicertutil sign /noinput c:\gemssql\tx109.exe
digicertutil sign /noinput c:\gemssql\tx110.exe
digicertutil sign /noinput c:\gemssql\tx112.exe
digicertutil sign /noinput c:\gemssql\tx113.exe
digicertutil sign /noinput c:\gemssql\tx114.exe
digicertutil sign /noinput c:\gemssql\tx115.exe
digicertutil sign /noinput c:\gemssql\tx116.exe
digicertutil sign /noinput c:\gemssql\tx117.exe
digicertutil sign /noinput c:\gemssql\tx118.exe
digicertutil sign /noinput c:\gemssql\tx201.exe
digicertutil sign /noinput c:\gemssql\tx203.exe
digicertutil sign /noinput c:\gemssql\tx210.exe
digicertutil sign /noinput c:\gemssql\tx211.exe
digicertutil sign /noinput c:\gemssql\tx301.exe
digicertutil sign /noinput c:\gemssql\tx302.exe
digicertutil sign /noinput c:\gemssql\tx303.exe
digicertutil sign /noinput c:\gemssql\tx304.exe
digicertutil sign /noinput c:\gemssql\tx310.exe
digicertutil sign /noinput c:\gemssql\tx311.exe
digicertutil sign /noinput c:\gemssql\tx312.exe
digicertutil sign /noinput c:\gemssql\tx313.exe
digicertutil sign /noinput c:\gemssql\tx314.exe
digicertutil sign /noinput c:\gemssql\tx340.exe
digicertutil sign /noinput c:\gemssql\tx350.exe
digicertutil sign /noinput c:\gemssql\tx351.exe
digicertutil sign /noinput c:\gemssql\tx352.exe
digicertutil sign /noinput c:\gemssql\tx401.exe
digicertutil sign /noinput c:\gemssql\tx402.exe
digicertutil sign /noinput c:\gemssql\tx404.exe
digicertutil sign /noinput c:\gemssql\tx405.exe
digicertutil sign /noinput c:\gemssql\tx405atest.exe
digicertutil sign /noinput c:\gemssql\tx406.exe
digicertutil sign /noinput c:\gemssql\tx407.exe
digicertutil sign /noinput c:\gemssql\tx410.exe
digicertutil sign /noinput c:\gemssql\tx411.exe
digicertutil sign /noinput c:\gemssql\tx412.exe
digicertutil sign /noinput c:\gemssql\tx430.exe
digicertutil sign /noinput c:\gemssql\tx501.exe
digicertutil sign /noinput c:\gemssql\tx505.exe
digicertutil sign /noinput c:\gemssql\tx506.exe
digicertutil sign /noinput c:\gemssql\tx600.exe
digicertutil sign /noinput c:\gemssql\tx702.exe
digicertutil sign /noinput c:\gemssql\tx801.exe
digicertutil sign /noinput c:\gemssql\tx802.exe
digicertutil sign /noinput c:\gemssql\tx808.exe
digicertutil sign /noinput c:\gemssql\tx809.exe
digicertutil sign /noinput c:\gemssql\tx810.exe
digicertutil sign /noinput c:\gemssql\tx816.exe
digicertutil sign /noinput c:\gemssql\tx830.exe
digicertutil sign /noinput c:\gemssql\tx901.exe
digicertutil sign /noinput c:\gemssql\tx902.exe
digicertutil sign /noinput c:\gemssql\tx903.exe
digicertutil sign /noinput c:\gemssql\tx904.exe
digicertutil sign /noinput c:\gemssql\txa01.exe
digicertutil sign /noinput c:\gemssql\txa02.exe
digicertutil sign /noinput c:\gemssql\txa03.exe
digicertutil sign /noinput c:\gemssql\txa04.exe
digicertutil sign /noinput c:\gemssql\txa05.exe
digicertutil sign /noinput c:\gemssql\txa06.exe
digicertutil sign /noinput c:\gemssql\txa08.exe
digicertutil sign /noinput c:\gemssql\txa09.exe
digicertutil sign /noinput c:\gemssql\txa12.exe
digicertutil sign /noinput c:\gemssql\txa30.exe
digicertutil sign /noinput c:\gemssql\txa31.exe
digicertutil sign /noinput c:\gemssql\txe02.exe
digicertutil sign /noinput c:\gemssql\txe03.exe
digicertutil sign /noinput c:\gemssql\txe04.exe
digicertutil sign /noinput c:\gemssql\txe05.exe
digicertutil sign /noinput c:\gemssql\txe06.exe
digicertutil sign /noinput c:\gemssql\txe08.exe
digicertutil sign /noinput c:\gemssql\txe09.exe
digicertutil sign /noinput c:\gemssql\txe10.exe
digicertutil sign /noinput c:\gemssql\txe11.exe
digicertutil sign /noinput c:\gemssql\txe12.exe
digicertutil sign /noinput c:\gemssql\txe13.exe
digicertutil sign /noinput c:\gemssql\txe14.exe
digicertutil sign /noinput c:\gemssql\txe15.exe
digicertutil sign /noinput c:\gemssql\txe16.exe
digicertutil sign /noinput c:\gemssql\txe17.exe
digicertutil sign /noinput c:\gemssql\txe18.exe
digicertutil sign /noinput c:\gemssql\txe20.exe
digicertutil sign /noinput c:\gemssql\txe21.exe
digicertutil sign /noinput c:\gemssql\txe24.exe
digicertutil sign /noinput c:\gemssql\txe25.exe
digicertutil sign /noinput c:\gemssql\txe26.exe
digicertutil sign /noinput c:\gemssql\txe40.exe
digicertutil sign /noinput c:\gemssql\txe42.exe
digicertutil sign /noinput c:\gemssql\txe43.exe
digicertutil sign /noinput c:\gemssql\txe44.exe
digicertutil sign /noinput c:\gemssql\txe44_clrbktx.exe
digicertutil sign /noinput c:\gemssql\txe45.exe
digicertutil sign /noinput c:\gemssql\txe46.exe
digicertutil sign /noinput c:\gemssql\txe47.exe
digicertutil sign /noinput c:\gemssql\txe48.exe
digicertutil sign /noinput c:\gemssql\txe49.exe
digicertutil sign /noinput c:\gemssql\txe50.exe
digicertutil sign /noinput c:\gemssql\txe51.exe
digicertutil sign /noinput c:\gemssql\txe52.exe
digicertutil sign /noinput c:\gemssql\txe53.exe
digicertutil sign /noinput c:\gemssql\txe54.exe
digicertutil sign /noinput c:\gemssql\txe55.exe
