SET PATH=%PATH%;C:\gemssql;
digicertutil sign /noinput c:\gemssql\ub101.exe
digicertutil sign /noinput c:\gemssql\ub102.exe
digicertutil sign /noinput c:\gemssql\ub103.exe
digicertutil sign /noinput c:\gemssql\ub104.exe
digicertutil sign /noinput c:\gemssql\ub105.exe
digicertutil sign /noinput c:\gemssql\ub106.exe
digicertutil sign /noinput c:\gemssql\ub107.exe
digicertutil sign /noinput c:\gemssql\ub108.exe
digicertutil sign /noinput c:\gemssql\ub109.exe
digicertutil sign /noinput c:\gemssql\ub110.exe
digicertutil sign /noinput c:\gemssql\ub111.exe
digicertutil sign /noinput c:\gemssql\ub112.exe
digicertutil sign /noinput c:\gemssql\ub202.exe
digicertutil sign /noinput c:\gemssql\ub203.exe
digicertutil sign /noinput c:\gemssql\ub204.exe
digicertutil sign /noinput c:\gemssql\ub207.exe
digicertutil sign /noinput c:\gemssql\ub210.exe
digicertutil sign /noinput c:\gemssql\ub211.exe
digicertutil sign /noinput c:\gemssql\ub212.exe
digicertutil sign /noinput c:\gemssql\ub213.exe
digicertutil sign /noinput c:\gemssql\ub214.exe
digicertutil sign /noinput c:\gemssql\ub230.exe
digicertutil sign /noinput c:\gemssql\ub231.exe
digicertutil sign /noinput c:\gemssql\ub232.exe
digicertutil sign /noinput c:\gemssql\ub233.exe
digicertutil sign /noinput c:\gemssql\ub234.exe
digicertutil sign /noinput c:\gemssql\ub235.exe
digicertutil sign /noinput c:\gemssql\ub302.exe
digicertutil sign /noinput c:\gemssql\ub304.exe
digicertutil sign /noinput c:\gemssql\ub305.exe
digicertutil sign /noinput c:\gemssql\ub306.exe
digicertutil sign /noinput c:\gemssql\ub340.exe
digicertutil sign /noinput c:\gemssql\ub341.exe
digicertutil sign /noinput c:\gemssql\ub401.exe
digicertutil sign /noinput c:\gemssql\ub402.exe
digicertutil sign /noinput c:\gemssql\ub404.exe
digicertutil sign /noinput c:\gemssql\ub411.exe
digicertutil sign /noinput c:\gemssql\ub412.exe
digicertutil sign /noinput c:\gemssql\ub413.exe
digicertutil sign /noinput c:\gemssql\ub414.exe
digicertutil sign /noinput c:\gemssql\ub430.exe
digicertutil sign /noinput c:\gemssql\ub501.exe
digicertutil sign /noinput c:\gemssql\ub502.exe
digicertutil sign /noinput c:\gemssql\ubcalcbill.exe
digicertutil sign /noinput c:\gemssql\ubcalcreading.exe
