<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="UB401" targetNamespace="http://tempuri.org/UB401.xsd" elementFormDefault="qualified" xmlns="http://tempuri.org/UB401.xsd" xmlns:mstns="http://tempuri.org/UB401.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="mytable">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="LISTNO" type="xs:integer" />
				<xs:element name="NAME" type="xs:string" />
				<xs:element name="UNBILLED" type="xs:decimal" />
				<xs:element name="OVERPAID" type="xs:decimal" />
				<xs:element name="BILLAMT" type="xs:decimal" />
				<xs:element name="ADJAMT" type="xs:decimal" />
				<xs:element name="ADJNO" type="xs:integer" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>