<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="TA103" targetNamespace="http://tempuri.org/TA103.xsd" elementFormDefault="qualified"
  xmlns="http://tempuri.org/TA103.xsd" xmlns:mstns="http://tempuri.org/TA103.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="TXCODE">
<xs:complexType>
<xs:sequence>
<xs:element name="TCCODE" type="xs:decimal" />
<xs:element name="TCTYPE" type="xs:string" />
<xs:element name="TCDESC" type="xs:string" />
<xs:element name="TCOPMC" type="xs:decimal" />
<xs:element name="TCGRP" type="xs:string" />
<xs:element name="TCSGRP" type="xs:string" />
<xs:element name="MVINST" type="xs:string" />
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>