<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="TX407" targetNamespace="http://tempuri.org/TX407.xsd" elementFormDefault="qualified"
  xmlns="http://tempuri.org/TX407.xsd" xmlns:mstns="http://tempuri.org/TX407.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="mytable">
<xs:complexType>
<xs:sequence>
<xs:element name="SEL" type="xs:boolean" />
<xs:element name="PCUST" type="xs:integer" />
<xs:element name="VEHID" type="xs:integer" />
<xs:element name="DMVNAME" type="xs:string" />
<xs:element name="DMVADDR" type="xs:string" />
<xs:element name="DMVCITY" type="xs:string" />
<xs:element name="DMVST" type="xs:string" />
<xs:element name="DMVZIP" type="xs:string" />
<xs:element name="NAME" type="xs:string" />
<xs:element name="ADDR" type="xs:string" />
<xs:element name="CITY" type="xs:string" />
<xs:element name="DOB" type="xs:integer" />
<xs:element name="MSG" type="xs:string" />
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>
