<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="TX406" targetNamespace="http://tempuri.org/TX406.xsd" elementFormDefault="qualified" xmlns="http://tempuri.org/TX406.xsd" xmlns:mstns="http://tempuri.org/TX406.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="mytable">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="LISTNO" type="xs:integer" />
        <xs:element name="YEAR" type="xs:integer" />
        <xs:element name="TYPEDESC" type="xs:string" />
        <xs:element name="NAME" type="xs:string" />
				<xs:element name="ORIGTAX" type="xs:decimal" />
				<xs:element name="TAX" type="xs:decimal" />
        <xs:element name="PAID" type="xs:decimal" />
        <xs:element name="BALANCE" type="xs:decimal" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>