<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="TA521" targetNamespace="http://tempuri.org/TA521.xsd" elementFormDefault="qualified" xmlns="http://tempuri.org/TA521.xsd" xmlns:mstns="http://tempuri.org/TA521.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="mytable">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="listno" type="xs:long" />
        <xs:element name="name" type="xs:string" />
        <xs:element name="class" type="xs:integer" />
        <xs:element name="regno" type="xs:string" />
        <xs:element name="olist" type="xs:long" />
        <xs:element name="gross" type="xs:long" />
        <xs:element name="ccno" type="xs:long" />
        <xs:element name="ccdate" type="xs:date" />
        <xs:element name="ccgross" type="xs:long" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>