<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="UB110" targetNamespace="http://tempuri.org/UB110.xsd" elementFormDefault="qualified"
  xmlns="http://tempuri.org/UB110.xsd" xmlns:mstns="http://tempuri.org/UB110.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="UTFMBILL">
<xs:complexType>
<xs:sequence>
<xs:element name="type" type="xs:string" />
<xs:element name="payto" type="xs:string" />
<xs:element name="line1" type="xs:string" />
<xs:element name="line2" type="xs:string" />
<xs:element name="line3" type="xs:string" />
<xs:element name="line4" type="xs:string" />
<xs:element name="line5" type="xs:string" />
<xs:element name="title" type="xs:string" />
<xs:element name="hours1" type="xs:string" />
<xs:element name="hours2" type="xs:string" />
<xs:element name="aphone" type="xs:string" />
<xs:element name="cphone" type="xs:string" />
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>