<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="FA200" targetNamespace="http://tempuri.org/FA200.xsd" elementFormDefault="qualified"
  xmlns="http://tempuri.org/FA200.xsd" xmlns:mstns="http://tempuri.org/FA200.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="mytable">
<xs:complexType>
<xs:sequence>
<xs:element name="GROUPID" type="xs:string" />
<xs:element name="TAG" type="xs:string" />
<xs:element name="DESC" type="xs:string" />
<xs:element name="DEPT" type="xs:string" />
<xs:element name="SERIAL" type="xs:string" />
<xs:element name="GLACCT1" type="xs:string" />
<xs:element name="GLACCT2" type="xs:string" />
<xs:element name="ACQVAL" type="xs:integer" />
<xs:element name="ACQDATE" type="xs:string" />
<xs:element name="LIFEYEARS" type="xs:integer" />
<xs:element name="LIFEDATE" type="xs:string" />
<xs:element name="BEFOREDEPRVAL" type="xs:decimal" />
<xs:element name="DEPRVAL" type="xs:decimal" />
<xs:element name="AFTERDEPRVAL" type="xs:decimal" />
<xs:element name="DSPVAL" type="xs:integer" />
<xs:element name="ASSETVAL" type="xs:decimal" />
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>