<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="TXE13" targetNamespace="http://tempuri.org/TXE13.xsd" elementFormDefault="qualified"
  xmlns="http://tempuri.org/TXE13.xsd" xmlns:mstns="http://tempuri.org/TXR05.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="mytable">
<xs:complexType>
<xs:sequence>
<xs:element name="GROUP" type="xs:string" />
<xs:element name="LISTNO" type="xs:integer" />
<xs:element name="YEAR" type="xs:integer" />
<xs:element name="TYPE" type="xs:string" />
<xs:element name="ADDR1" type="xs:string" />
<xs:element name="ADDR2" type="xs:string" />
<xs:element name="ADDR3" type="xs:string" />
<xs:element name="ADDR4" type="xs:string" />
<xs:element name="ADDR5" type="xs:string" />
<xs:element name="TAXT" type="xs:decimal" />
<xs:element name="PAID" type="xs:decimal" />
<xs:element name="STARTOVER" type="xs:decimal" />
<xs:element name="OVRPAID" type="xs:decimal" />
<xs:element name="LASTPAIDDT" type="xs:date" />
<xs:element name="CCNO" type="xs:integer" />
<xs:element name="CCDATE" type="xs:date" />
<xs:element name="CCRESN" type="xs:string" />
<xs:element name="BKCD" type="xs:string" />
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>