<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="TXE43" targetNamespace="http://tempuri.org/TXE43.xsd" elementFormDefault="qualified"
  xmlns="http://tempuri.org/TXE43.xsd" xmlns:mstns="http://tempuri.org/TXR05.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="mytable">
<xs:complexType>
<xs:sequence>
<xs:element name="LISTNO" type="xs:integer" />
<xs:element name="YEAR" type="xs:integer" />
<xs:element name="TYPE" type="xs:string" />
<xs:element name="NAME" type="xs:string" />
<xs:element name="ADDR1" type="xs:string" />
<xs:element name="ADDR2" type="xs:string" />
<xs:element name="ADDR3" type="xs:string" />
<xs:element name="DESC" type="xs:string" />
<xs:element name="NET" type="xs:long" />
<xs:element name="BALANCE" type="xs:decimal" />
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>
