<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="AP504" targetNamespace="http://tempuri.org/AP504.xsd" elementFormDefault="qualified" xmlns="http://tempuri.org/AP504.xsd" xmlns:mstns="http://tempuri.org/AP504.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="mytable">
		<xs:complexType>
			<xs:sequence>
        <xs:element name="CHECKNO" type="xs:integer" />
				<xs:element name="CHKDATE" type="xs:date" />
				<xs:element name="AMOUNT" type="xs:decimal" />
				<xs:element name="NAME" type="xs:string" />
        <xs:element name="STATUS" type="xs:string" />
        <xs:element name="RECDATE" type="xs:date" />
      </xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>