<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="PO301" targetNamespace="http://tempuri.org/PO301.xsd" elementFormDefault="qualified"
  xmlns="http://tempuri.org/PO301.xsd" xmlns:mstns="http://tempuri.org/PO301.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="mytable">
<xs:complexType>
<xs:sequence>
  <xs:element name="LLOCN" type="xs:string" />
  <xs:element name="BCHNO" type="xs:integer" />
  <xs:element name="PONBR" type="xs:integer" />
  <xs:element name="PODATE" type="xs:date" />
  <xs:element name="VENDOR" type="xs:string" />
  <xs:element name="VENNM" type="xs:string" />
  <xs:element name="SNAME" type="xs:string" />
  <xs:element name="SADR1" type="xs:string" />
  <xs:element name="SADR2" type="xs:string" />
  <xs:element name="SADR3" type="xs:string" />
  <xs:element name="SADR4" type="xs:string" />
  <xs:element name="SZIP" type="xs:string" />
  <xs:element name="SZIPE" type="xs:string" />
  <xs:element name="RNAME" type="xs:string" />
  <xs:element name="RADR1" type="xs:string" />
  <xs:element name="RADR2" type="xs:string" />
  <xs:element name="RADR3" type="xs:string" />
  <xs:element name="RADR4" type="xs:string" />
  <xs:element name="RZIP" type="xs:string" />
  <xs:element name="RZIPE" type="xs:string" />
  <xs:element name="ORDSP" type="xs:decimal" />
  <xs:element name="ACCTDISC" type="xs:string" />
  <xs:element name="ORSHP" type="xs:decimal" />
  <xs:element name="ACCTSHIP" type="xs:string" />
  <xs:element name="TOTAMT" type="xs:decimal" />
  <xs:element name="DISCOUNT" type="xs:decimal" />
  <xs:element name="SHIPPING" type="xs:decimal" />
  <xs:element name="TOTNET" type="xs:decimal" />
  <xs:element name="POSEQ" type="xs:integer" />
  <xs:element name="ITNBR" type="xs:string" />
  <xs:element name="ITDSC" type="xs:string" />
  <xs:element name="RQQTY" type="xs:integer" />
  <xs:element name="UNITP" type="xs:decimal" />
  <xs:element name="EXVAL" type="xs:decimal" />
  <xs:element name="UNMSR" type="xs:string" />
  <xs:element name="ACCT" type="xs:string" />
  <xs:element name="ACCTDESC" type="xs:string" />
  <xs:element name="ERRMSG" type="xs:string" />
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>