<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="TX505" targetNamespace="http://tempuri.org/TX505.xsd" elementFormDefault="qualified"
  xmlns="http://tempuri.org/TX505.xsd" xmlns:mstns="http://tempuri.org/TX505.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="mytable">
<xs:complexType>
<xs:sequence>
<xs:element name="BANKSV" type="xs:string" />
<xs:element name="BANKCD" type="xs:string" />
<xs:element name="LISTNO" type="xs:integer" />
<xs:element name="NAME" type="xs:string" />
<xs:element name="SNAME" type="xs:string" />
<xs:element name="ADDRCTYST" type="xs:string" />
<xs:element name="LOCATION" type="xs:string" />
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>