<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="PO201B" targetNamespace="http://tempuri.org/PO201B.xsd" elementFormDefault="qualified"
  xmlns="http://tempuri.org/PO201B.xsd" xmlns:mstns="http://tempuri.org/PO201B.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="mytable">
<xs:complexType>
<xs:sequence>
<xs:element name="BCHNO" type="xs:integer" />
<xs:element name="BCHDATE" type="xs:date" />
<xs:element name="FUND" type="xs:integer" />
<xs:element name="GROUP" type="xs:string" />
<xs:element name="TRNTYP" type="xs:string" />
<xs:element name="GLTYP" type="xs:string" />
<xs:element name="DEBIT" type="xs:decimal" />
<xs:element name="CREDIT" type="xs:decimal" />
<xs:element name="ACCT" type="xs:string" />
<xs:element name="ACCTDESCR" type="xs:string" />
<xs:element name="ERRMSG" type="xs:string" />
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>