<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="UB230"
                  targetNamespace="http://tempuri.org/UB230.xsd"
                  elementFormDefault="qualified"
                  xmlns="http://tempuri.org/UB230.xsd"
                  xmlns:mstns="http://tempuri.org/UB230.xsd"
                  xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="mytable">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="LISTNO" type="xs:integer" />
				<xs:element name="YEAR" type="xs:integer" />
				<xs:element name="BILLTYPE" type="xs:string" />
				<xs:element name="NAME" type="xs:string" />
				<xs:element name="PROPLOC" type="xs:string" />
				<xs:element name="AMT1" type="xs:decimal" />
				<xs:element name="AMT2" type="xs:decimal" />
				<xs:element name="AMT3" type="xs:decimal" />
				<xs:element name="AMT4" type="xs:decimal" />
				<xs:element name="AMT5" type="xs:decimal" />
        <xs:element name="AMT6" type="xs:decimal" />
        <xs:element name="USERAMT1" type="xs:decimal" />
        <xs:element name="USERAMT2" type="xs:decimal" />
        <xs:element name="USERAMT3" type="xs:decimal" />
        <xs:element name="BILLAMT" type="xs:decimal" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>
