<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="UB236" targetNamespace="http://tempuri.org/UB236.xsd" elementFormDefault="qualified"
  xmlns="http://tempuri.org/UB236.xsd" xmlns:mstns="http://tempuri.org/UB236.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="mytable">
<xs:complexType>
<xs:sequence>
<xs:element name="SORTDATA" type="xs:string" />
<xs:element name="RPTID" type="xs:string" />
<xs:element name="LISTNO" type="xs:integer" />
<xs:element name="ADDR1" type="xs:string" />
<xs:element name="ADDR2" type="xs:string" />
<xs:element name="ADDR3" type="xs:string" />
<xs:element name="ADDR4" type="xs:string" />
<xs:element name="ADDR5" type="xs:string" />
<xs:element name="CMXREF" type="xs:string" />
<xs:element name="METERUSE" type="xs:long" />
<xs:element name="METERREAD" type="xs:long" />
<xs:element name="EDU" type="xs:decimal" />
<xs:element name="CMDESC1" type="xs:string" />
<xs:element name="CMDESC2" type="xs:string" />
<xs:element name="CMREAD" type="xs:integer" />
<xs:element name="CMUSE" type="xs:integer" />
<xs:element name="XREFEDU" type="xs:decimal" />
<xs:element name="XREFPCT" type="xs:decimal" />
<xs:element name="USEDESC" type="xs:string" />
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>