<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="TX407B" targetNamespace="http://tempuri.org/TX407B.xsd" elementFormDefault="qualified"
  xmlns="http://tempuri.org/TX407B.xsd" xmlns:mstns="http://tempuri.org/TX407B.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="mytable">
<xs:complexType>
<xs:sequence>
<xs:element name="REGNO" type="xs:string" />
<xs:element name="LIST" type="xs:integer" />
<xs:element name="TYPE" type="xs:string" />
<xs:element name="YEAR" type="xs:integer" />
<xs:element name="NAME" type="xs:string" />
<xs:element name="ADDR" type="xs:string" />
<xs:element name="MSG" type="xs:string" />
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>
