<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="AP403"
                  targetNamespace="http://tempuri.org/AP403.xsd"
                  elementFormDefault="qualified"
                  xmlns="http://tempuri.org/AP403.xsd"
                  xmlns:mstns="http://tempuri.org/AP403.xsd"
                  xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="mytable">
      <xs:complexType>
        <xs:sequence>
          <xs:element name="CHECKNO" type="xs:integer" />
          <xs:element name="CHECKDT" type="xs:date" />
          <xs:element name="VNDNR" type="xs:string" />
          <xs:element name="NAME" type="xs:string" />
          <xs:element name="PAYAMT" type="xs:decimal" />
          <xs:element name="PONBR" type="xs:integer" />
          <xs:element name="DESCR" type="xs:string" />
          <xs:element name="ACCTFULL" type="xs:string" />
          <xs:element name="FUND" type="xs:string" />
          <xs:element name="DEPT" type="xs:string" />
          <xs:element name="OBJECT" type="xs:string" />
          <xs:element name="FUNCTION" type="xs:string" />
        </xs:sequence>
      </xs:complexType>
    </xs:element>
  </xs:schema>
