<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="AP403GL"
                  targetNamespace="http://tempuri.org/AP403GL.xsd"
                  elementFormDefault="qualified"
                  xmlns="http://tempuri.org/AP403GL.xsd"
                  xmlns:mstns="http://tempuri.org/AP403GL.xsd"
                  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="mytable">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="CHECKDT" type="xs:date" />
        <xs:element name="ACCTNO" type="xs:string" />
        <xs:element name="ACCTDESC" type="xs:string" />
        <xs:element name="ACCTTYPE" type="xs:string" />
        <xs:element name="TRANTYPE" type="xs:string" />
        <xs:element name="CREDIT" type="xs:decimal" />
        <xs:element name="DEBIT" type="xs:decimal" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
