'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.Serializable(),  _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
 Global.System.ComponentModel.ToolboxItem(true),  _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 Global.System.Xml.Serialization.XmlRootAttribute("TO206"),  _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class TO206
    Inherits Global.System.Data.DataSet
    
    Private tablemytable As mytableDataTable
    
    Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet()
            ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("mytable")) Is Nothing) Then
                MyBase.Tables.Add(New mytableDataTable(ds.Tables("mytable")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property mytable() As mytableDataTable
        Get
            Return Me.tablemytable
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.BrowsableAttribute(true),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Overrides Function Clone() As Global.System.Data.DataSet
        Dim cln As TO206 = CType(MyBase.Clone,TO206)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet()
            ds.ReadXml(reader)
            If (Not (ds.Tables("mytable")) Is Nothing) Then
                MyBase.Tables.Add(New mytableDataTable(ds.Tables("mytable")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
        Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
        Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tablemytable = CType(MyBase.Tables("mytable"),mytableDataTable)
        If (initTable = true) Then
            If (Not (Me.tablemytable) Is Nothing) Then
                Me.tablemytable.InitVars
            End If
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Private Sub InitClass()
        Me.DataSetName = "TO206"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/TO206.xsd"
        Me.Locale = New Global.System.Globalization.CultureInfo("")
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
        Me.tablemytable = New mytableDataTable()
        MyBase.Tables.Add(Me.tablemytable)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Private Function ShouldSerializemytable() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
        Dim ds As TO206 = New TO206()
        Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType()
        Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence()
        Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
        If xs.Contains(dsSchema.TargetNamespace) Then
            Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
            Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
            Try 
                Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                dsSchema.Write(s1)
                Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                Do While schemas.MoveNext
                    schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                    s2.SetLength(0)
                    schema.Write(s2)
                    If (s1.Length = s2.Length) Then
                        s1.Position = 0
                        s2.Position = 0
                        
                        Do While ((s1.Position <> s1.Length)  _
                                    AndAlso (s1.ReadByte = s2.ReadByte))
                            
                            
                        Loop
                        If (s1.Position = s1.Length) Then
                            Return type
                        End If
                    End If
                    
                Loop
            Finally
                If (Not (s1) Is Nothing) Then
                    s1.Close
                End If
                If (Not (s2) Is Nothing) Then
                    s2.Close
                End If
            End Try
        End If
        xs.Add(dsSchema)
        Return type
    End Function
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Delegate Sub mytableRowChangeEventHandler(ByVal sender As Object, ByVal e As mytableRowChangeEvent)
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class mytableDataTable
        Inherits Global.System.Data.TypedTableBase(Of mytableRow)
        
        Private columnAddress As Global.System.Data.DataColumn
        
        Private columnTownZip As Global.System.Data.DataColumn
        
        Private columnPhone As Global.System.Data.DataColumn
        
        Private columnEMail As Global.System.Data.DataColumn
        
        Private columnMunTown As Global.System.Data.DataColumn
        
        Private columnMunBur As Global.System.Data.DataColumn
        
        Private columnMunCity As Global.System.Data.DataColumn
        
        Private columnDistFire As Global.System.Data.DataColumn
        
        Private columnDistSewer As Global.System.Data.DataColumn
        
        Private columnDistLighting As Global.System.Data.DataColumn
        
        Private columnDistVillage As Global.System.Data.DataColumn
        
        Private columnDistBeach As Global.System.Data.DataColumn
        
        Private columnDistImprovement As Global.System.Data.DataColumn
        
        Private columnDistOther As Global.System.Data.DataColumn
        
        Private columnCollApp As Global.System.Data.DataColumn
        
        Private columnCollElect As Global.System.Data.DataColumn
        
        Private columnMillRateDay As Global.System.Data.DataColumn
        
        Private columnMillRateMonth As Global.System.Data.DataColumn
        
        Private columnMillRate As Global.System.Data.DataColumn
        
        Private columnMillRateMV As Global.System.Data.DataColumn
        
        Private columnMillRateAuthority As Global.System.Data.DataColumn
        
        Private columnCreditCardYes As Global.System.Data.DataColumn
        
        Private columnCreditCardNo As Global.System.Data.DataColumn
        
        Private columnCollected As Global.System.Data.DataColumn
        
        Private columnCreditAllYes As Global.System.Data.DataColumn
        
        Private columnCreditAllNo As Global.System.Data.DataColumn
        
        Private columnCreditRestrict As Global.System.Data.DataColumn
        
        Private columnLiensYes As Global.System.Data.DataColumn
        
        Private columnLiensNo As Global.System.Data.DataColumn
        
        Private columntotre As Global.System.Data.DataColumn
        
        Private columntotmv As Global.System.Data.DataColumn
        
        Private columntotpp As Global.System.Data.DataColumn
        
        Private columntot As Global.System.Data.DataColumn
        
        Private columntotsu As Global.System.Data.DataColumn
        
        Private columnREDueDate1 As Global.System.Data.DataColumn
        
        Private columnREDueDate2 As Global.System.Data.DataColumn
        
        Private columnREDueDate3 As Global.System.Data.DataColumn
        
        Private columnREDueDate4 As Global.System.Data.DataColumn
        
        Private columnPPDueDate1 As Global.System.Data.DataColumn
        
        Private columnPPDueDate2 As Global.System.Data.DataColumn
        
        Private columnPPDueDate3 As Global.System.Data.DataColumn
        
        Private columnPPDueDate4 As Global.System.Data.DataColumn
        
        Private columnMVDueDate1 As Global.System.Data.DataColumn
        
        Private columnMVDueDate2 As Global.System.Data.DataColumn
        
        Private columnMVDueDate3 As Global.System.Data.DataColumn
        
        Private columnMVDueDate4 As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "mytable"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property AddressColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnAddress
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property TownZipColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnTownZip
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property PhoneColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPhone
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property EMailColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnEMail
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property MunTownColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMunTown
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property MunBurColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMunBur
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property MunCityColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMunCity
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property DistFireColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDistFire
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property DistSewerColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDistSewer
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property DistLightingColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDistLighting
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property DistVillageColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDistVillage
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property DistBeachColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDistBeach
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property DistImprovementColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDistImprovement
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property DistOtherColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDistOther
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property CollAppColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCollApp
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property CollElectColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCollElect
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property MillRateDayColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMillRateDay
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property MillRateMonthColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMillRateMonth
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property MillRateColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMillRate
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property MillRateMVColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMillRateMV
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property MillRateAuthorityColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMillRateAuthority
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property CreditCardYesColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCreditCardYes
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property CreditCardNoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCreditCardNo
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property CollectedColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCollected
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property CreditAllYesColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCreditAllYes
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property CreditAllNoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCreditAllNo
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property CreditRestrictColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCreditRestrict
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property LiensYesColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnLiensYes
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property LiensNoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnLiensNo
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property totreColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columntotre
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property totmvColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columntotmv
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property totppColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columntotpp
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property totColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columntot
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property totsuColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columntotsu
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property REDueDate1Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnREDueDate1
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property REDueDate2Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnREDueDate2
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property REDueDate3Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnREDueDate3
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property REDueDate4Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnREDueDate4
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property PPDueDate1Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnPPDueDate1
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property PPDueDate2Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnPPDueDate2
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property PPDueDate3Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnPPDueDate3
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property PPDueDate4Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnPPDueDate4
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property MVDueDate1Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnMVDueDate1
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property MVDueDate2Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnMVDueDate2
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property MVDueDate3Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnMVDueDate3
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property MVDueDate4Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnMVDueDate4
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As mytableRow
            Get
                Return CType(Me.Rows(index),mytableRow)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event mytableRowChanging As mytableRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event mytableRowChanged As mytableRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event mytableRowDeleting As mytableRowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event mytableRowDeleted As mytableRowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Overloads Sub AddmytableRow(ByVal row As mytableRow)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Overloads Function AddmytableRow( _
                    ByVal Address As String,  _
                    ByVal TownZip As String,  _
                    ByVal Phone As String,  _
                    ByVal EMail As String,  _
                    ByVal MunTown As String,  _
                    ByVal MunBur As String,  _
                    ByVal MunCity As String,  _
                    ByVal DistFire As String,  _
                    ByVal DistSewer As String,  _
                    ByVal DistLighting As String,  _
                    ByVal DistVillage As String,  _
                    ByVal DistBeach As String,  _
                    ByVal DistImprovement As String,  _
                    ByVal DistOther As String,  _
                    ByVal CollApp As String,  _
                    ByVal CollElect As String,  _
                    ByVal MillRateDay As String,  _
                    ByVal MillRateMonth As String,  _
                    ByVal MillRate As Decimal,  _
                    ByVal MillRateMV As Decimal,  _
                    ByVal MillRateAuthority As String,  _
                    ByVal CreditCardYes As String,  _
                    ByVal CreditCardNo As String,  _
                    ByVal Collected As Decimal,  _
                    ByVal CreditAllYes As String,  _
                    ByVal CreditAllNo As String,  _
                    ByVal CreditRestrict As String,  _
                    ByVal LiensYes As String,  _
                    ByVal LiensNo As String,  _
                    ByVal totre As Decimal,  _
                    ByVal totmv As Decimal,  _
                    ByVal totpp As Decimal,  _
                    ByVal tot As Decimal,  _
                    ByVal totsu As Decimal,  _
                    ByVal REDueDate1 As String,  _
                    ByVal REDueDate2 As String,  _
                    ByVal REDueDate3 As String,  _
                    ByVal REDueDate4 As String,  _
                    ByVal PPDueDate1 As String,  _
                    ByVal PPDueDate2 As String,  _
                    ByVal PPDueDate3 As String,  _
                    ByVal PPDueDate4 As String,  _
                    ByVal MVDueDate1 As String,  _
                    ByVal MVDueDate2 As String,  _
                    ByVal MVDueDate3 As String,  _
                    ByVal MVDueDate4 As String) As mytableRow
            Dim rowmytableRow As mytableRow = CType(Me.NewRow,mytableRow)
            Dim columnValuesArray() As Object = New Object() {Address, TownZip, Phone, EMail, MunTown, MunBur, MunCity, DistFire, DistSewer, DistLighting, DistVillage, DistBeach, DistImprovement, DistOther, CollApp, CollElect, MillRateDay, MillRateMonth, MillRate, MillRateMV, MillRateAuthority, CreditCardYes, CreditCardNo, Collected, CreditAllYes, CreditAllNo, CreditRestrict, LiensYes, LiensNo, totre, totmv, totpp, tot, totsu, REDueDate1, REDueDate2, REDueDate3, REDueDate4, PPDueDate1, PPDueDate2, PPDueDate3, PPDueDate4, MVDueDate1, MVDueDate2, MVDueDate3, MVDueDate4}
            rowmytableRow.ItemArray = columnValuesArray
            Me.Rows.Add(rowmytableRow)
            Return rowmytableRow
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As mytableDataTable = CType(MyBase.Clone,mytableDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New mytableDataTable()
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Friend Sub InitVars()
            Me.columnAddress = MyBase.Columns("Address")
            Me.columnTownZip = MyBase.Columns("TownZip")
            Me.columnPhone = MyBase.Columns("Phone")
            Me.columnEMail = MyBase.Columns("EMail")
            Me.columnMunTown = MyBase.Columns("MunTown")
            Me.columnMunBur = MyBase.Columns("MunBur")
            Me.columnMunCity = MyBase.Columns("MunCity")
            Me.columnDistFire = MyBase.Columns("DistFire")
            Me.columnDistSewer = MyBase.Columns("DistSewer")
            Me.columnDistLighting = MyBase.Columns("DistLighting")
            Me.columnDistVillage = MyBase.Columns("DistVillage")
            Me.columnDistBeach = MyBase.Columns("DistBeach")
            Me.columnDistImprovement = MyBase.Columns("DistImprovement")
            Me.columnDistOther = MyBase.Columns("DistOther")
            Me.columnCollApp = MyBase.Columns("CollApp")
            Me.columnCollElect = MyBase.Columns("CollElect")
            Me.columnMillRateDay = MyBase.Columns("MillRateDay")
            Me.columnMillRateMonth = MyBase.Columns("MillRateMonth")
            Me.columnMillRate = MyBase.Columns("MillRate")
            Me.columnMillRateMV = MyBase.Columns("MillRateMV")
            Me.columnMillRateAuthority = MyBase.Columns("MillRateAuthority")
            Me.columnCreditCardYes = MyBase.Columns("CreditCardYes")
            Me.columnCreditCardNo = MyBase.Columns("CreditCardNo")
            Me.columnCollected = MyBase.Columns("Collected")
            Me.columnCreditAllYes = MyBase.Columns("CreditAllYes")
            Me.columnCreditAllNo = MyBase.Columns("CreditAllNo")
            Me.columnCreditRestrict = MyBase.Columns("CreditRestrict")
            Me.columnLiensYes = MyBase.Columns("LiensYes")
            Me.columnLiensNo = MyBase.Columns("LiensNo")
            Me.columntotre = MyBase.Columns("totre")
            Me.columntotmv = MyBase.Columns("totmv")
            Me.columntotpp = MyBase.Columns("totpp")
            Me.columntot = MyBase.Columns("tot")
            Me.columntotsu = MyBase.Columns("totsu")
            Me.columnREDueDate1 = MyBase.Columns("REDueDate1")
            Me.columnREDueDate2 = MyBase.Columns("REDueDate2")
            Me.columnREDueDate3 = MyBase.Columns("REDueDate3")
            Me.columnREDueDate4 = MyBase.Columns("REDueDate4")
            Me.columnPPDueDate1 = MyBase.Columns("PPDueDate1")
            Me.columnPPDueDate2 = MyBase.Columns("PPDueDate2")
            Me.columnPPDueDate3 = MyBase.Columns("PPDueDate3")
            Me.columnPPDueDate4 = MyBase.Columns("PPDueDate4")
            Me.columnMVDueDate1 = MyBase.Columns("MVDueDate1")
            Me.columnMVDueDate2 = MyBase.Columns("MVDueDate2")
            Me.columnMVDueDate3 = MyBase.Columns("MVDueDate3")
            Me.columnMVDueDate4 = MyBase.Columns("MVDueDate4")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Private Sub InitClass()
            Me.columnAddress = New Global.System.Data.DataColumn("Address", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnAddress)
            Me.columnTownZip = New Global.System.Data.DataColumn("TownZip", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTownZip)
            Me.columnPhone = New Global.System.Data.DataColumn("Phone", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPhone)
            Me.columnEMail = New Global.System.Data.DataColumn("EMail", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnEMail)
            Me.columnMunTown = New Global.System.Data.DataColumn("MunTown", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMunTown)
            Me.columnMunBur = New Global.System.Data.DataColumn("MunBur", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMunBur)
            Me.columnMunCity = New Global.System.Data.DataColumn("MunCity", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMunCity)
            Me.columnDistFire = New Global.System.Data.DataColumn("DistFire", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDistFire)
            Me.columnDistSewer = New Global.System.Data.DataColumn("DistSewer", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDistSewer)
            Me.columnDistLighting = New Global.System.Data.DataColumn("DistLighting", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDistLighting)
            Me.columnDistVillage = New Global.System.Data.DataColumn("DistVillage", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDistVillage)
            Me.columnDistBeach = New Global.System.Data.DataColumn("DistBeach", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDistBeach)
            Me.columnDistImprovement = New Global.System.Data.DataColumn("DistImprovement", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDistImprovement)
            Me.columnDistOther = New Global.System.Data.DataColumn("DistOther", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDistOther)
            Me.columnCollApp = New Global.System.Data.DataColumn("CollApp", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCollApp)
            Me.columnCollElect = New Global.System.Data.DataColumn("CollElect", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCollElect)
            Me.columnMillRateDay = New Global.System.Data.DataColumn("MillRateDay", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMillRateDay)
            Me.columnMillRateMonth = New Global.System.Data.DataColumn("MillRateMonth", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMillRateMonth)
            Me.columnMillRate = New Global.System.Data.DataColumn("MillRate", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMillRate)
            Me.columnMillRateMV = New Global.System.Data.DataColumn("MillRateMV", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMillRateMV)
            Me.columnMillRateAuthority = New Global.System.Data.DataColumn("MillRateAuthority", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMillRateAuthority)
            Me.columnCreditCardYes = New Global.System.Data.DataColumn("CreditCardYes", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCreditCardYes)
            Me.columnCreditCardNo = New Global.System.Data.DataColumn("CreditCardNo", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCreditCardNo)
            Me.columnCollected = New Global.System.Data.DataColumn("Collected", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCollected)
            Me.columnCreditAllYes = New Global.System.Data.DataColumn("CreditAllYes", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCreditAllYes)
            Me.columnCreditAllNo = New Global.System.Data.DataColumn("CreditAllNo", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCreditAllNo)
            Me.columnCreditRestrict = New Global.System.Data.DataColumn("CreditRestrict", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCreditRestrict)
            Me.columnLiensYes = New Global.System.Data.DataColumn("LiensYes", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnLiensYes)
            Me.columnLiensNo = New Global.System.Data.DataColumn("LiensNo", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnLiensNo)
            Me.columntotre = New Global.System.Data.DataColumn("totre", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columntotre)
            Me.columntotmv = New Global.System.Data.DataColumn("totmv", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columntotmv)
            Me.columntotpp = New Global.System.Data.DataColumn("totpp", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columntotpp)
            Me.columntot = New Global.System.Data.DataColumn("tot", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columntot)
            Me.columntotsu = New Global.System.Data.DataColumn("totsu", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columntotsu)
            Me.columnREDueDate1 = New Global.System.Data.DataColumn("REDueDate1", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnREDueDate1)
            Me.columnREDueDate2 = New Global.System.Data.DataColumn("REDueDate2", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnREDueDate2)
            Me.columnREDueDate3 = New Global.System.Data.DataColumn("REDueDate3", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnREDueDate3)
            Me.columnREDueDate4 = New Global.System.Data.DataColumn("REDueDate4", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnREDueDate4)
            Me.columnPPDueDate1 = New Global.System.Data.DataColumn("PPDueDate1", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPPDueDate1)
            Me.columnPPDueDate2 = New Global.System.Data.DataColumn("PPDueDate2", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPPDueDate2)
            Me.columnPPDueDate3 = New Global.System.Data.DataColumn("PPDueDate3", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPPDueDate3)
            Me.columnPPDueDate4 = New Global.System.Data.DataColumn("PPDueDate4", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPPDueDate4)
            Me.columnMVDueDate1 = New Global.System.Data.DataColumn("MVDueDate1", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMVDueDate1)
            Me.columnMVDueDate2 = New Global.System.Data.DataColumn("MVDueDate2", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMVDueDate2)
            Me.columnMVDueDate3 = New Global.System.Data.DataColumn("MVDueDate3", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMVDueDate3)
            Me.columnMVDueDate4 = New Global.System.Data.DataColumn("MVDueDate4", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMVDueDate4)
            Me.columnAddress.AllowDBNull = false
            Me.columnTownZip.AllowDBNull = false
            Me.columnPhone.AllowDBNull = false
            Me.columnEMail.AllowDBNull = false
            Me.columnMunTown.AllowDBNull = false
            Me.columnMunBur.AllowDBNull = false
            Me.columnMunCity.AllowDBNull = false
            Me.columnDistFire.AllowDBNull = false
            Me.columnDistSewer.AllowDBNull = false
            Me.columnDistLighting.AllowDBNull = false
            Me.columnDistVillage.AllowDBNull = false
            Me.columnDistBeach.AllowDBNull = false
            Me.columnDistImprovement.AllowDBNull = false
            Me.columnDistOther.AllowDBNull = false
            Me.columnCollApp.AllowDBNull = false
            Me.columnCollElect.AllowDBNull = false
            Me.columnMillRateDay.AllowDBNull = false
            Me.columnMillRateMonth.AllowDBNull = false
            Me.columnMillRate.AllowDBNull = false
            Me.columnMillRateMV.AllowDBNull = false
            Me.columnMillRateAuthority.AllowDBNull = false
            Me.columnCreditCardYes.AllowDBNull = false
            Me.columnCreditCardNo.AllowDBNull = false
            Me.columnCollected.AllowDBNull = false
            Me.columnCreditAllYes.AllowDBNull = false
            Me.columnCreditAllNo.AllowDBNull = false
            Me.columnCreditRestrict.AllowDBNull = false
            Me.columnLiensYes.AllowDBNull = false
            Me.columnLiensNo.AllowDBNull = false
            Me.columntotre.AllowDBNull = false
            Me.columntotmv.AllowDBNull = false
            Me.columntotpp.AllowDBNull = false
            Me.columntot.AllowDBNull = false
            Me.columntotsu.AllowDBNull = false
            Me.columnREDueDate1.AllowDBNull = false
            Me.columnREDueDate2.AllowDBNull = false
            Me.columnREDueDate3.AllowDBNull = false
            Me.columnREDueDate4.AllowDBNull = false
            Me.columnPPDueDate1.AllowDBNull = false
            Me.columnPPDueDate2.AllowDBNull = false
            Me.columnPPDueDate3.AllowDBNull = false
            Me.columnPPDueDate4.AllowDBNull = false
            Me.columnMVDueDate1.AllowDBNull = false
            Me.columnMVDueDate2.AllowDBNull = false
            Me.columnMVDueDate3.AllowDBNull = false
            Me.columnMVDueDate4.AllowDBNull = false
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function NewmytableRow() As mytableRow
            Return CType(Me.NewRow,mytableRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New mytableRow(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(mytableRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.mytableRowChangedEvent) Is Nothing) Then
                RaiseEvent mytableRowChanged(Me, New mytableRowChangeEvent(CType(e.Row,mytableRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.mytableRowChangingEvent) Is Nothing) Then
                RaiseEvent mytableRowChanging(Me, New mytableRowChangeEvent(CType(e.Row,mytableRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.mytableRowDeletedEvent) Is Nothing) Then
                RaiseEvent mytableRowDeleted(Me, New mytableRowChangeEvent(CType(e.Row,mytableRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.mytableRowDeletingEvent) Is Nothing) Then
                RaiseEvent mytableRowDeleting(Me, New mytableRowChangeEvent(CType(e.Row,mytableRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub RemovemytableRow(ByVal row As mytableRow)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType()
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence()
            Dim ds As TO206 = New TO206()
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute()
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute()
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "mytableDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    Partial Public Class mytableRow
        Inherits Global.System.Data.DataRow
        
        Private tablemytable As mytableDataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tablemytable = CType(Me.Table,mytableDataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property Address() As String
            Get
                Return CType(Me(Me.tablemytable.AddressColumn),String)
            End Get
            Set
                Me(Me.tablemytable.AddressColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property TownZip() As String
            Get
                Return CType(Me(Me.tablemytable.TownZipColumn),String)
            End Get
            Set
                Me(Me.tablemytable.TownZipColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property Phone() As String
            Get
                Return CType(Me(Me.tablemytable.PhoneColumn),String)
            End Get
            Set
                Me(Me.tablemytable.PhoneColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property EMail() As String
            Get
                Return CType(Me(Me.tablemytable.EMailColumn),String)
            End Get
            Set
                Me(Me.tablemytable.EMailColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property MunTown() As String
            Get
                Return CType(Me(Me.tablemytable.MunTownColumn),String)
            End Get
            Set
                Me(Me.tablemytable.MunTownColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property MunBur() As String
            Get
                Return CType(Me(Me.tablemytable.MunBurColumn),String)
            End Get
            Set
                Me(Me.tablemytable.MunBurColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property MunCity() As String
            Get
                Return CType(Me(Me.tablemytable.MunCityColumn),String)
            End Get
            Set
                Me(Me.tablemytable.MunCityColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property DistFire() As String
            Get
                Return CType(Me(Me.tablemytable.DistFireColumn),String)
            End Get
            Set
                Me(Me.tablemytable.DistFireColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property DistSewer() As String
            Get
                Return CType(Me(Me.tablemytable.DistSewerColumn),String)
            End Get
            Set
                Me(Me.tablemytable.DistSewerColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property DistLighting() As String
            Get
                Return CType(Me(Me.tablemytable.DistLightingColumn),String)
            End Get
            Set
                Me(Me.tablemytable.DistLightingColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property DistVillage() As String
            Get
                Return CType(Me(Me.tablemytable.DistVillageColumn),String)
            End Get
            Set
                Me(Me.tablemytable.DistVillageColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property DistBeach() As String
            Get
                Return CType(Me(Me.tablemytable.DistBeachColumn),String)
            End Get
            Set
                Me(Me.tablemytable.DistBeachColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property DistImprovement() As String
            Get
                Return CType(Me(Me.tablemytable.DistImprovementColumn),String)
            End Get
            Set
                Me(Me.tablemytable.DistImprovementColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property DistOther() As String
            Get
                Return CType(Me(Me.tablemytable.DistOtherColumn),String)
            End Get
            Set
                Me(Me.tablemytable.DistOtherColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property CollApp() As String
            Get
                Return CType(Me(Me.tablemytable.CollAppColumn),String)
            End Get
            Set
                Me(Me.tablemytable.CollAppColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property CollElect() As String
            Get
                Return CType(Me(Me.tablemytable.CollElectColumn),String)
            End Get
            Set
                Me(Me.tablemytable.CollElectColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property MillRateDay() As String
            Get
                Return CType(Me(Me.tablemytable.MillRateDayColumn),String)
            End Get
            Set
                Me(Me.tablemytable.MillRateDayColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property MillRateMonth() As String
            Get
                Return CType(Me(Me.tablemytable.MillRateMonthColumn),String)
            End Get
            Set
                Me(Me.tablemytable.MillRateMonthColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property MillRate() As Decimal
            Get
                Return CType(Me(Me.tablemytable.MillRateColumn),Decimal)
            End Get
            Set
                Me(Me.tablemytable.MillRateColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property MillRateMV() As Decimal
            Get
                Return CType(Me(Me.tablemytable.MillRateMVColumn),Decimal)
            End Get
            Set
                Me(Me.tablemytable.MillRateMVColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property MillRateAuthority() As String
            Get
                Return CType(Me(Me.tablemytable.MillRateAuthorityColumn),String)
            End Get
            Set
                Me(Me.tablemytable.MillRateAuthorityColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property CreditCardYes() As String
            Get
                Return CType(Me(Me.tablemytable.CreditCardYesColumn),String)
            End Get
            Set
                Me(Me.tablemytable.CreditCardYesColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property CreditCardNo() As String
            Get
                Return CType(Me(Me.tablemytable.CreditCardNoColumn),String)
            End Get
            Set
                Me(Me.tablemytable.CreditCardNoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property Collected() As Decimal
            Get
                Return CType(Me(Me.tablemytable.CollectedColumn),Decimal)
            End Get
            Set
                Me(Me.tablemytable.CollectedColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property CreditAllYes() As String
            Get
                Return CType(Me(Me.tablemytable.CreditAllYesColumn),String)
            End Get
            Set
                Me(Me.tablemytable.CreditAllYesColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property CreditAllNo() As String
            Get
                Return CType(Me(Me.tablemytable.CreditAllNoColumn),String)
            End Get
            Set
                Me(Me.tablemytable.CreditAllNoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property CreditRestrict() As String
            Get
                Return CType(Me(Me.tablemytable.CreditRestrictColumn),String)
            End Get
            Set
                Me(Me.tablemytable.CreditRestrictColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property LiensYes() As String
            Get
                Return CType(Me(Me.tablemytable.LiensYesColumn),String)
            End Get
            Set
                Me(Me.tablemytable.LiensYesColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property LiensNo() As String
            Get
                Return CType(Me(Me.tablemytable.LiensNoColumn),String)
            End Get
            Set
                Me(Me.tablemytable.LiensNoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property totre() As Decimal
            Get
                Return CType(Me(Me.tablemytable.totreColumn),Decimal)
            End Get
            Set
                Me(Me.tablemytable.totreColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property totmv() As Decimal
            Get
                Return CType(Me(Me.tablemytable.totmvColumn),Decimal)
            End Get
            Set
                Me(Me.tablemytable.totmvColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property totpp() As Decimal
            Get
                Return CType(Me(Me.tablemytable.totppColumn),Decimal)
            End Get
            Set
                Me(Me.tablemytable.totppColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property tot() As Decimal
            Get
                Return CType(Me(Me.tablemytable.totColumn),Decimal)
            End Get
            Set
                Me(Me.tablemytable.totColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property totsu() As Decimal
            Get
                Return CType(Me(Me.tablemytable.totsuColumn),Decimal)
            End Get
            Set
                Me(Me.tablemytable.totsuColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property REDueDate1() As String
            Get
                Return CType(Me(Me.tablemytable.REDueDate1Column),String)
            End Get
            Set
                Me(Me.tablemytable.REDueDate1Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property REDueDate2() As String
            Get
                Return CType(Me(Me.tablemytable.REDueDate2Column),String)
            End Get
            Set
                Me(Me.tablemytable.REDueDate2Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property REDueDate3() As String
            Get
                Return CType(Me(Me.tablemytable.REDueDate3Column),String)
            End Get
            Set
                Me(Me.tablemytable.REDueDate3Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property REDueDate4() As String
            Get
                Return CType(Me(Me.tablemytable.REDueDate4Column),String)
            End Get
            Set
                Me(Me.tablemytable.REDueDate4Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property PPDueDate1() As String
            Get
                Return CType(Me(Me.tablemytable.PPDueDate1Column),String)
            End Get
            Set
                Me(Me.tablemytable.PPDueDate1Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property PPDueDate2() As String
            Get
                Return CType(Me(Me.tablemytable.PPDueDate2Column),String)
            End Get
            Set
                Me(Me.tablemytable.PPDueDate2Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property PPDueDate3() As String
            Get
                Return CType(Me(Me.tablemytable.PPDueDate3Column),String)
            End Get
            Set
                Me(Me.tablemytable.PPDueDate3Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property PPDueDate4() As String
            Get
                Return CType(Me(Me.tablemytable.PPDueDate4Column),String)
            End Get
            Set
                Me(Me.tablemytable.PPDueDate4Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property MVDueDate1() As String
            Get
                Return CType(Me(Me.tablemytable.MVDueDate1Column),String)
            End Get
            Set
                Me(Me.tablemytable.MVDueDate1Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property MVDueDate2() As String
            Get
                Return CType(Me(Me.tablemytable.MVDueDate2Column),String)
            End Get
            Set
                Me(Me.tablemytable.MVDueDate2Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property MVDueDate3() As String
            Get
                Return CType(Me(Me.tablemytable.MVDueDate3Column),String)
            End Get
            Set
                Me(Me.tablemytable.MVDueDate3Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property MVDueDate4() As String
            Get
                Return CType(Me(Me.tablemytable.MVDueDate4Column),String)
            End Get
            Set
                Me(Me.tablemytable.MVDueDate4Column) = value
            End Set
        End Property
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Class mytableRowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As mytableRow
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub New(ByVal row As mytableRow, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property Row() As mytableRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class






