<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="TXE04Tot" targetNamespace="http://tempuri.org/TXE04Tot.xsd" elementFormDefault="qualified"
  xmlns="http://tempuri.org/TXE04Tot.xsd" xmlns:mstns="http://tempuri.org/TXE04Tot.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="mytable2">
<xs:complexType>
<xs:sequence>
<xs:element name="YEAR" type="xs:integer" />
<xs:element name="TYPE" type="xs:string" />
<xs:element name="LETTER" type="xs:string" />
<xs:element name="TCOUNT" type="xs:integer" />
<xs:element name="TTAX" type="xs:double" />
<xs:element name="TPAID" type="xs:double" />
<xs:element name="TDUE" type="xs:double" />
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>