<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="GL402" targetNamespace="http://tempuri.org/GL402.xsd" elementFormDefault="qualified"
  xmlns="http://tempuri.org/GL402.xsd" xmlns:mstns="http://tempuri.org/GL402.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="mytable">
<xs:complexType>
<xs:sequence>
<xs:element name="ACCT" type="xs:string" />
<xs:element name="BCHNO" type="xs:integer" />
<xs:element name="DATED" type="xs:date" />
<xs:element name="GLTYP" type="xs:string" />
<xs:element name="TRTYP" type="xs:string" />
<xs:element name="SRCDE" type="xs:string" />
<xs:element name="DEBIT" type="xs:decimal" />
<xs:element name="CREDIT" type="xs:decimal" />
<xs:element name="TDESC" type="xs:string" />
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>