<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="UB409" targetNamespace="http://tempuri.org/UB409.xsd" elementFormDefault="qualified"
  xmlns="http://tempuri.org/UB409.xsd" xmlns:mstns="http://tempuri.org/UB409.xsd"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="mytable">
<xs:complexType>
<xs:sequence>
<xs:element name="LISTNO" type="xs:integer" />
<xs:element name="YEAR" type="xs:integer" />
<xs:element name="BILLTYPE" type="xs:string" />
<xs:element name="RATECODE" type="xs:string" />
<xs:element name="ADDR1" type="xs:string" />
<xs:element name="ADDR2" type="xs:string" />
<xs:element name="ADDR3" type="xs:string" />
<xs:element name="ADDR4" type="xs:string" />
<xs:element name="ADDR5" type="xs:string" />
<xs:element name="PROPLOC" type="xs:string" />
<xs:element name="UNITS" type="xs:decimal" />
<xs:element name="USAGE" type="xs:integer" />
<xs:element name="BILLAMT" type="xs:decimal" />
<xs:element name="BALANCE" type="xs:decimal" />
<xs:element name="INTEREST" type="xs:decimal" />
<xs:element name="LIEN" type="xs:decimal" />
<xs:element name="TAXTOT" type="xs:decimal" />
<xs:element name="BILLAMTA" type="xs:decimal" />
<xs:element name="BILLAMTB" type="xs:decimal" />
<xs:element name="BILLAMTC" type="xs:decimal" />
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>
