<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="TA216Tot" targetNamespace="http://tempuri.org/TA216Tot.xsd" elementFormDefault="qualified" xmlns="http://tempuri.org/TA216Tot.xsd" xmlns:mstns="http://tempuri.org/TA216Tot.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="mytable">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="CODE" type="xs:integer" />
        <xs:element name="DESCR" type="xs:string" />
        <xs:element name="COUNT" type="xs:integer" />
        <xs:element name="ACRES" type="xs:decimal" />
        <xs:element name="FOREST" type="xs:decimal" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>