<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="TXE26Tot" targetNamespace="http://tempuri.org/TXE26Tot.xsd" elementFormDefault="qualified"
  xmlns="http://tempuri.org/TXE26Tot.xsd" xmlns:mstns="http://tempuri.org/TXE26Tot.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="mytable2">
<xs:complexType>
<xs:sequence>
<xs:element name="TCOUNT" type="xs:integer" />
<xs:element name="TPRINPAID" type="xs:double" />
<xs:element name="TFEEPAID" type="xs:double" />
<xs:element name="TINTPAID" type="xs:double" />
<xs:element name="TLIENPAID" type="xs:double" />
<xs:element name="TTOTPAID" type="xs:double" />
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>