<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="TA212RE" targetNamespace="http://tempuri.org/TA212RE.xsd" elementFormDefault="qualified"
  xmlns="http://tempuri.org/TA212RE.xsd" xmlns:mstns="http://tempuri.org/TA212RE.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="mytable">
<xs:complexType>
<xs:sequence>
<xs:element name="DIST" type="xs:integer" />
<xs:element name="FRCD" type="xs:string" />
<xs:element name="FRCDDESC" type="xs:string" />
<xs:element name="LISTNO" type="xs:long" />
<xs:element name="LISTA" type="xs:string" />
<xs:element name="YEAR" type="xs:long" />
<xs:element name="TYPEDESC" type="xs:string" />
<xs:element name="ADDR1" type="xs:string" />
<xs:element name="ADDR2" type="xs:string" />
<xs:element name="ADDR3" type="xs:string" />
<xs:element name="ADDR4" type="xs:string" />
<xs:element name="ADDR5" type="xs:string" />
<xs:element name="LOCATION" type="xs:string" />
<xs:element name="PROPDESC" type="xs:string" />
<xs:element name="VOLPAGE" type="xs:string" />
<xs:element name="MAPLOT" type="xs:string" />
<xs:element name="FULLGROSS" type="xs:long" />
<xs:element name="PIEXM" type="xs:long" />
<xs:element name="GROSS" type="xs:long" />
<xs:element name="EXEMPT" type="xs:long" />
<xs:element name="NET" type="xs:long" />
<xs:element name="ASSCD1" type="xs:string" />
<xs:element name="ASSAMT1" type="xs:long" />
<xs:element name="ASSCD2" type="xs:string" />
<xs:element name="ASSAMT2" type="xs:long" />
<xs:element name="ASSCD3" type="xs:string" />
<xs:element name="ASSAMT3" type="xs:long" />
<xs:element name="ASSCD4" type="xs:string" />
<xs:element name="ASSAMT4" type="xs:long" />
<xs:element name="ASSCD5" type="xs:string" />
<xs:element name="ASSAMT5" type="xs:long" />
<xs:element name="ASSCD6" type="xs:string" />
<xs:element name="ASSAMT6" type="xs:long" />
<xs:element name="ASSCD7" type="xs:string" />
<xs:element name="ASSAMT7" type="xs:long" />
<xs:element name="EXCD1" type="xs:string" />
<xs:element name="EXAMT1" type="xs:long" />
<xs:element name="EXCD2" type="xs:string" />
<xs:element name="EXAMT2" type="xs:long" />
<xs:element name="EXCD3" type="xs:string" />
<xs:element name="EXAMT3" type="xs:long" />
<xs:element name="EXCD4" type="xs:string" />
<xs:element name="EXAMT4" type="xs:long" />
<xs:element name="EXCD5" type="xs:string" />
<xs:element name="EXAMT5" type="xs:long" />
<xs:element name="EXCD6" type="xs:string" />
<xs:element name="EXAMT6" type="xs:long" />
<xs:element name="EXCD7" type="xs:string" />
<xs:element name="EXAMT7" type="xs:long" />
<xs:element name="CCNO" type="xs:long" />
<xs:element name="CCDATE" type="xs:date" />
<xs:element name="CCGRS" type="xs:long" />
<xs:element name="CCEX" type="xs:long" />
<xs:element name="CCNET" type="xs:long" />
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>