<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="TAB02" targetNamespace="http://tempuri.org/TAB02.xsd" elementFormDefault="qualified" xmlns="http://tempuri.org/TAB02.xsd" xmlns:mstns="http://tempuri.org/TAB02.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="mytable">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="listno" type="xs:long" />
        <xs:element name="type" type="xs:string" />
        <xs:element name="addr1" type="xs:string" />
        <xs:element name="addr2" type="xs:string" />
        <xs:element name="addr3" type="xs:string" />
        <xs:element name="addr4" type="xs:string" />
        <xs:element name="addr5" type="xs:string" />
        <xs:element name="excd" type="xs:string" />
        <xs:element name="exam" type="xs:integer" />
        <xs:element name="exdesc" type="xs:string" />
        <xs:element name="revloss" type="xs:decimal" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
