<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="TA513" targetNamespace="http://tempuri.org/TA513.xsd" elementFormDefault="qualified"
  xmlns="http://tempuri.org/TA513.xsd" xmlns:mstns="http://tempuri.org/TA513.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="mytable">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="LISTNO" type="xs:integer" />
        <xs:element name="ADDR1" type="xs:string" />
        <xs:element name="ADDR2" type="xs:string" />
        <xs:element name="ADDR3" type="xs:string" />
        <xs:element name="ADDR4" type="xs:string" />
        <xs:element name="ADDR5" type="xs:string" />
        <xs:element name="VALUE" type="xs:integer" />
        <xs:element name="CLASS" type="xs:integer" />
        <xs:element name="MAKE" type="xs:string" />
        <xs:element name="YEAR" type="xs:integer" />
        <xs:element name="VINNO" type="xs:string" />
        <xs:element name="MODEL" type="xs:string" />
        <xs:element name="BODY" type="xs:string" />
        <xs:element name="LWT" type="xs:integer" />
        <xs:element name="GWT" type="xs:integer" />
        <xs:element name="REGNO" type="xs:string" />
        <xs:element name="SEAT" type="xs:integer" />
        <xs:element name="PCLR" type="xs:string" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>