<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="TS005" targetNamespace="http://tempuri.org/TS005.xsd" elementFormDefault="qualified" xmlns="http://tempuri.org/TS005.xsd" xmlns:mstns="http://tempuri.org/TS005.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="mytable">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="SORTBY" type="xs:string" />
        <xs:element type="xs:date" name="MFTDAT" />
        <xs:element name="MFTTIM" type="xs:integer" />
        <xs:element name="MFYEAR" type="xs:integer" />
        <xs:element name="MFCLS" type="xs:string" />
        <xs:element name="MFNAM" type="xs:string" />
        <xs:element name="MFADD1" type="xs:string" />
        <xs:element name="MFPERNO" type="xs:integer" />
        <xs:element name="MFLFEE" type="xs:double" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>