<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="TAP03" 
  targetNamespace="http://tempuri.org/TAP03.xsd"
  elementFormDefault="qualified" 
  xmlns="http://tempuri.org/TAP03.xsd"
  xmlns:mstns="http://tempuri.org/TAP03.xsd"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="mytable">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="listno" type="xs:integer" />
        <xs:element name="name" type="xs:string" />
				<xs:element name="code" type="xs:integer" />
        <xs:element name="desc" type="xs:string" />
        <xs:element name="depr" type="xs:integer" />
        <xs:element name="net" type="xs:integer" />
      </xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>
