<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="TO113" targetNamespace="http://tempuri.org/TO113.xsd" elementFormDefault="qualified" xmlns="http://tempuri.org/TO113.xsd" xmlns:mstns="http://tempuri.org/TO113.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="mytable">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="LISTNO" type="xs:integer" />
        <xs:element name="NAME" type="xs:string" />
        <xs:element name="GROSS" type="xs:integer" />
        <xs:element name="TOTBTR" type="xs:integer" />
        <xs:element name="NEWGROSS" type="xs:integer" />
        <xs:element name="ERRMSG" type="xs:string" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>