<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="AP702" targetNamespace="http://tempuri.org/AP702.xsd" elementFormDefault="qualified" xmlns="http://tempuri.org/AP702.xsd" xmlns:mstns="http://tempuri.org/AP312.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="mytable">
		<xs:complexType>
			<xs:sequence>
        <xs:element name="VNDNR" type="xs:string" />
        <xs:element name="ATAXID" type="xs:string" />
        <xs:element name="VENNM" type="xs:string" />
        <xs:element name="VADD1" type="xs:string" />
        <xs:element name="VADD2" type="xs:string" />
        <xs:element name="VADD3" type="xs:string" />
        <xs:element name="VADD4" type="xs:string" />
        <xs:element name="PYNAM" type="xs:string" />
        <xs:element name="PYAD1" type="xs:string" />
        <xs:element name="PYAD2" type="xs:string" />
        <xs:element name="PYAD3" type="xs:string" />
        <xs:element name="PYAD4" type="xs:string" />
        <xs:element name="AMTPD" type="xs:decimal" />
      </xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>