<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="TO207" targetNamespace="http://tempuri.org/TO207.xsd" elementFormDefault="qualified" xmlns="http://tempuri.org/TO207.xsd" xmlns:mstns="http://tempuri.org/TO207.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="mytable">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="LISTNO" type="xs:integer" />
        <xs:element name="YEAR" type="xs:integer" />
        <xs:element name="TYPE" type="xs:string" />
        <xs:element name="NAME" type="xs:string" />
        <xs:element name="EXEMPTVET" type="xs:decimal" />
        <xs:element name="TAXLOSSVET" type="xs:decimal" />
        <xs:element name="EXEMPTADDL" type="xs:decimal" />
        <xs:element name="TAXLOSSADDL" type="xs:decimal" />
        <xs:element name="APPTYPE" type="xs:string" />
        <xs:element name="ASSN" type="xs:integer" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>