<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="TXA09VAL"
                  targetNamespace="http://tempuri.org/TXA09VAL.xsd"
                  elementFormDefault="qualified"
                  xmlns="http://tempuri.org/TXA09VAL.xsd"
                  xmlns:mstns="http://tempuri.org/TXA09VAL.xsd"
                  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="mytable">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="LISTNO" type="xs:integer" />
        <xs:element name="YEAR" type="xs:integer" />
        <xs:element name="TYPE" type="xs:string" />
        <xs:element name="TYPEDESC" type="xs:string" />
        <xs:element name="SEQ" type="xs:integer" />
        <xs:element name="NAME" type="xs:string" />
        <xs:element name="PROPDESC" type="xs:string" />
        <xs:element name="PROPDESC2" type="xs:string" />
        <xs:element name="PRINCIPAL" type="xs:decimal" />
        <xs:element name="INTEREST" type="xs:decimal" />
        <xs:element name="LIENS" type="xs:decimal" />
        <xs:element name="FEES" type="xs:decimal" />
				<xs:element name="BOND" type="xs:decimal" />
				<xs:element name="TOTAL" type="xs:decimal" />
        <xs:element name="BATCH" type="xs:string" />
        <xs:element name="BATCHNO" type="xs:integer" />
        <xs:element name="RECDT" type="xs:date" />
        <xs:element name="CASH" type="xs:decimal" />
        <xs:element name="CHECK" type="xs:decimal" />
        <xs:element name="CREDIT" type="xs:decimal" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
