<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="TXA05" targetNamespace="http://tempuri.org/TXA05.xsd" elementFormDefault="qualified" xmlns="http://tempuri.org/TXA05.xsd" xmlns:mstns="http://tempuri.org/TXA05.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="mytable">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="LISTNO" type="xs:integer" />
				<xs:element name="YEAR" type="xs:integer" />
				<xs:element name="TYPE" type="xs:string" />
				<xs:element name="NAME" type="xs:string" />
				<xs:element name="BALANCE" type="xs:decimal" />
				<xs:element name="OVER" type="xs:decimal" />
				<xs:element name="UNDER" type="xs:decimal" />
				<xs:element name="LASTPAIDDT" type="xs:date" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>