<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="TO103" targetNamespace="http://tempuri.org/TO103.xsd" elementFormDefault="qualified" xmlns="http://tempuri.org/TO103.xsd" xmlns:mstns="http://tempuri.org/TO103.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="mytable">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="listno" type="xs:long" />
        <xs:element name="name" type="xs:string" />
        <xs:element name="sname" type="xs:string" />
        <xs:element name="proploc" type="xs:string" />
        <xs:element name="year" type="xs:integer" />
        <xs:element name="code" type="xs:string" />
        <xs:element name="netass" type="xs:integer" />
        <xs:element name="tax" type="xs:decimal" />
        <xs:element name="adjtax" type="xs:decimal" />
        <xs:element name="taxcredit" type="xs:decimal" />
        <xs:element name="msg" type="xs:string" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>