<?xml version="1.0" encoding="utf-8" ?> 
<xs:schema id="TA212TotExempt" 
                  targetNamespace="http://tempuri.org/TA212TotExempt.xsd"
                  elementFormDefault="qualified"
                  xmlns="http://tempuri.org/TA212TotExempt.xsd"
                  xmlns:mstns="http://tempuri.org/TA212TotExempt.xsd"
                  xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="mytableexempt">
<xs:complexType>
<xs:sequence>
<xs:element name="texemptletter" type="xs:string" />
<xs:element name="texemptcode" type="xs:string" />
<xs:element name="texemptdesc" type="xs:string" />
<xs:element name="texemptcount" type="xs:integer" />
<xs:element name="texemptgross" type="xs:long" />
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>
