<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="TXE49" targetNamespace="http://tempuri.org/TXE49.xsd" elementFormDefault="qualified" xmlns="http://tempuri.org/TXE49.xsd" xmlns:mstns="http://tempuri.org/TXE49.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="mytable">
        <xs:complexType>
            <xs:sequence>
              <xs:element name="LISTNO" type="xs:integer" />
							<xs:element name="NAME" type="xs:string" />
              <xs:element name="SNAME" type="xs:string" />
              <xs:element name="ADDR1" type="xs:string" />
              <xs:element name="ADDR2" type="xs:string" />
              <xs:element name="CITY" type="xs:string" />
              <xs:element name="ZIPA" type="xs:string" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>