<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="MR200" targetNamespace="http://tempuri.org/MR200.xsd" 
  elementFormDefault="qualified"
  xmlns="http://tempuri.org/MR200.xsd"
  xmlns:mstns="http://tempuri.org/MR200.xsd"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="mytable">
<xs:complexType>
<xs:sequence>
<xs:element name="BATCHNO" type="xs:integer" />
<xs:element name="DATE" type="xs:date" />
<xs:element name="CODE" type="xs:string" />
<xs:element name="DESCR" type="xs:string" />
<xs:element name="CASH" type="xs:decimal" />
<xs:element name="CHECK" type="xs:decimal" />
<xs:element name="CREDIT" type="xs:decimal" />
<xs:element name="TOTAL" type="xs:decimal" />
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>