<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="GL403" targetNamespace="http://tempuri.org/GL403.xsd" elementFormDefault="qualified"
  xmlns="http://tempuri.org/GL403.xsd" xmlns:mstns="http://tempuri.org/GL403.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="mytable">
<xs:complexType>
<xs:sequence>
<xs:element name="BCHNO" type="xs:integer" />
<xs:element name="GROUP" type="xs:string" />
<xs:element name="TRNBR" type="xs:integer" />
<xs:element name="JRNSEQ" type="xs:integer" />
<xs:element name="TRNTYP" type="xs:string" />
<xs:element name="GLTYP" type="xs:string" />
<xs:element name="ACDATE" type="xs:date" />
<xs:element name="DEBIT" type="xs:decimal" />
<xs:element name="CREDIT" type="xs:decimal" />
<xs:element name="DESCR" type="xs:string" />
<xs:element name="ACCT" type="xs:string" />
<xs:element name="ACCTDESCR" type="xs:string" />
<xs:element name="REFNO" type="xs:integer" />
<xs:element name="ERRMSG" type="xs:string" />
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>