alter table ACCNARL add primary key (FUND, SFUND, DEPT, OBJ, FUNC, SFUNC, SEQ4)
alter table APEBCH add primary key (BCHNO,SEQNO)
alter table APEBNC add primary key (BNKCD)
alter table APEBNK add primary key (BNKCD)
alter table APEOPN add primary key (VNDNR, INVNO, RECNO)
drop index asna_key_apctrll1 on apctrl
alter table APERCN add primary key (PAYBN, PAYCK, RCCDE)
alter table APCTRL add primary key (TNBR)
alter table AP1099P add primary key (AYEAR, ARACCT)
alter table ARCUST add primary key (CUSN)
alter table BCHHDR add primary key (APPID, BCHNO)
alter table BUDNAR add primary key (FUND, SFUND, DEPT, OBJ, FUNC, SFUNC, SEQ)
alter table CSHBCH add primary key (BCHNO, RECNO)
alter table DEPNARL add primary key (DEPT, SEQ4)
alter table FNDSEC add primary key (USRPRF, FDNBR)
alter table GLACCT add primary key (FDNBR, SFUND, DPNBR, OBNBR, FNPGM, SUBFN)
alter table GLBUDGET add primary key (FUND, SFUND, DEPT, OBJ, FUNC, SFUNC)
alter table GLDEP add primary key (DEPT)
alter table GLDEPGRP add primary key (CODE)
alter table GLEBCH add primary key (BCHNO, TRNBR, JRNSEQ)
alter table GLEDOBJ add primary key (FSCYR, FDNBR, SFUND, DPNBR, OBNBR)
alter table GLEDSUM add primary key (FSCYR, FDNBR, SFUND, DPNBR, OBNBR, FNPGM, SUBFN)
alter table GLACCT add primary key (FDNBR, SFUND, DPNBR, OBNBR, FNPGM, SUBFN)
alter table GLFUND add primary key (FDNBR, SFUND)
alter table GLGRUP add primary key ([GROUP])
alter table GLHEAD add primary key (FDNBR, SFUND)
alter table GLOBJT add primary key (OBNBR)
alter table GLPROG add primary key (FNPGM)
alter table GLRBCH add primary key (BCHNO, TRNBR, JRNSEQ)
alter table GLSUBF add primary key (SUBFN)
alter table GNET add primary key (CODE)
alter table GLTYPE add primary key (GLTYP)
alter table LOCATN add primary key (LLOCN)
alter table LOCSEC add primary key (USRPRF,LLOCN)
alter table MRBCH add primary key (BCHNO)
alter table MRBCHD add primary key (BCHNO,CODE)
alter table MRCNTL add primary key (RECID)
alter table MRCODE add primary key (CODE)
alter table MRHST add primary key (BCHNO,CODE,CHDATE)
alter table MSCBCH add primary key (BCHNO,TRNBR,JRNSEQ)
alter table MUNLED add primary key (CODE)
alter table MUNMIL add primary key (CODE)
alter table MUNMILD add primary key (YEAR)
alter table POMAST add primary key (FSCYR, PONBR, POSUF, POSEQ, RSQDG, BCHNO)
alter table POMEMO add primary key (FDNBR, SFUND, LNE)
alter table POMBCH add primary key (BCHNO, PONBR)
alter table POMBCD add primary key (BCHNO, PONBR, POSEQ)
alter table POSUMF add primary key (FSCYR, PONBR, ACCT)
alter table PURCTL add primary key (FSCYR)
alter table RQEBCH add primary key (LLOCN, BCHNO, RQNBR)
alter table RQEBCD add primary key (LLOCN, BCHNO, RQNBR, RQSEQ)
alter table TOWN add primary key (CEREC)
alter table VENCAT add primary key (VNCAT)
alter table VENDOR add primary key (VNDNR)