/****** Object:  Table [dbo].[DEPSEC]    Script Date: 12/20/2021 12:50:08 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DEPSEC](
	[USRPRF] [char](20) NOT NULL,
	[FUND] [numeric](3, 0) NOT NULL,
	[SFUND] [numeric](3, 0) NOT NULL,
	[DEPT] [numeric](4, 0) NOT NULL,
 CONSTRAINT [PK_GLBUDSEC] PRIMARY KEY CLUSTERED 
(
	[USRPRF] ASC,
	[FUND] ASC,
	[SFUND] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


