SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TXLOCDA](
	[YEAR] [numeric](4, 0) NOT NULL,
	[MAXTAX] [numeric](11, 2) NOT NULL,
	[TRFADJ] [numeric](5, 0) NOT NULL
PRIMARY KEY CLUSTERED 
(
	[YEAR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

