/****** Object:  Table [dbo].[APEBCD]    Script Date: 10/20/2020 11:53:08 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[APEBCD](
	[BCHNO] [decimal](5, 0) NOT NULL,
	[SEQNO] [decimal](4, 0) NOT NULL,
	[RECNO] [decimal](4, 0) NOT NULL,
	[FDNBR] [numeric](3, 0) NOT NULL,
	[SFUND] [numeric](3, 0) NOT NULL,
	[DPNBR] [numeric](4, 0) NOT NULL,
	[OBNBR] [numeric](3, 0) NOT NULL,
	[FNPGM] [numeric](4, 0) NOT NULL,
	[SUBFN] [numeric](4, 0) NOT NULL,
	[AMTNT] [decimal](11, 2) NOT NULL,
	[FA] [char](1) NOT NULL,
 CONSTRAINT [PK_APEBCHD] PRIMARY KEY CLUSTERED 
(
	[BCHNO] ASC,
	[SEQNO] ASC,
	[RECNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[APEBCD] ADD  CONSTRAINT [DF__APEBCHD__RECNO__2FF123C1]  DEFAULT ((0)) FOR [BCHNO]
GO

ALTER TABLE [dbo].[APEBCD] ADD  CONSTRAINT [DF__APEBCHD__RECNO__2FFB99C1]  DEFAULT ((0)) FOR [RECNO]
GO

ALTER TABLE [dbo].[APEBCD] ADD  CONSTRAINT [DF__APEBCHD__FDNBR__3C6170A6]  DEFAULT ((0)) FOR [FDNBR]
GO

ALTER TABLE [dbo].[APEBCD] ADD  CONSTRAINT [DF__APEBCHD__SFUND__3D5594DF]  DEFAULT ((0)) FOR [SFUND]
GO

ALTER TABLE [dbo].[APEBCD] ADD  CONSTRAINT [DF__APEBCHD__DPNBR__3E49B918]  DEFAULT ((0)) FOR [DPNBR]
GO

ALTER TABLE [dbo].[APEBCD] ADD  CONSTRAINT [DF__APEBCHD__OBNBR__3F3DDD51]  DEFAULT ((0)) FOR [OBNBR]
GO

ALTER TABLE [dbo].[APEBCD] ADD  CONSTRAINT [DF__APEBCHD__FNPGM__4032018A]  DEFAULT ((0)) FOR [FNPGM]
GO

ALTER TABLE [dbo].[APEBCD] ADD  CONSTRAINT [DF__APEBCHD__SUBFN__412625C3]  DEFAULT ((0)) FOR [SUBFN]
GO

ALTER TABLE [dbo].[APEBCD] ADD  CONSTRAINT [DF__APEBCHD__AMTNT__34C04EDE]  DEFAULT ((0)) FOR [AMTNT]
GO

ALTER TABLE [dbo].[APEBCD] ADD  CONSTRAINT [DF__APEBCHD__FA__47D32352]  DEFAULT ('') FOR [FA]
GO


