SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TXDEFER](
	[YEAR] [numeric](4, 0) NOT NULL,
	[CODE] [char](3) NOT NULL,
	[INTPCT] [numeric](4, 3) NOT NULL
PRIMARY KEY CLUSTERED 
(
	[YEAR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

