/****** Object:  Table [dbo].[POMBCD]    Script Date: 12/11/2020 8:04:33 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[POMBCD](
	[BCHNO] [decimal](3, 0) NOT NULL,
	[PONBR] [numeric](6, 0) NOT NULL,
	[POSEQ] [numeric](4, 0) NOT NULL,
	[RQQTY] [decimal](9, 2) NOT NULL,
	[ITNBR] [char](20) NOT NULL,
	[FDNBR] [numeric](3, 0) NOT NULL,
	[SFUND] [numeric](3, 0) NOT NULL,
	[DPNBR] [numeric](4, 0) NOT NULL,
	[OBNBR] [numeric](3, 0) NOT NULL,
	[FNPGM] [numeric](4, 0) NOT NULL,
	[SUBFN] [numeric](4, 0) NOT NULL,
	[UNITP] [decimal](10, 4) NOT NULL,
	[ITDSC] [char](30) NOT NULL,
	[UNMSR] [char](4) NOT NULL,
	[EXVAL] [decimal](11, 2) NOT NULL,
	[TOTVL] [decimal](11, 2) NOT NULL,
	[FA] [char](1) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[BCHNO] ASC,
	[PONBR] ASC,
	[POSEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [ASNA_KEY_POMBCD] UNIQUE NONCLUSTERED 
(
	[BCHNO] ASC,
	[PONBR] ASC,
	[POSEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[POMBCD] ADD  CONSTRAINT [DF_POMBCD_FA]  DEFAULT ('') FOR [FA]
GO


