DROP INDEX [ASNA_KEY_TXDCPP] ON [dbo].[TXDCPP]
DROP INDEX [ASNA_KEY_TXINV] ON [dbo].[TXINV]
DROP INDEX [ASNA_KEY_TXINVLD] ON [dbo].[TXINV]
DROP INDEX [ASNA_KEY_TXINVLE] ON [dbo].[TXINV]
DROP INDEX [ASNA_KEY_TXINVLK] ON [dbo].[TXINV]
DROP INDEX [ASNA_KEY_TXINVLP] ON [dbo].[TXINV]
DROP INDEX [ASNA_KEY_TXINVO] ON [dbo].[TXINVO]
DROP INDEX [ASNA_KEY_TXHSTL1] ON [dbo].[TXHST]
DROP INDEX [ASNA_KEY_TXHSTLC] ON [dbo].[TXHST]
DROP INDEX [ASNA_KEY_TXPPRP] ON [dbo].[TXPPRP]
DROP INDEX [ASNA_KEY_TXPPRPC] ON [dbo].[TXPPRPC]
DROP INDEX [ASNA_KEY_TXREAL] ON [dbo].[TXREAL]
DROP INDEX [ASNA_KEY_TXREALC] ON [dbo].[TXREALC]
DROP INDEX [ASNA_KEY_TXSUPP] ON [dbo].[TXSUPP]
DROP INDEX [ASNA_KEY_UTCUST] ON [dbo].[UTCUST]
GO


