drop table BDCNTL
drop table BDCOM
drop table BDCON
drop table BDENDRS
drop table BDMAST
drop table BDPAYCR
drop table BDRATE
drop table CKHIST
drop table FAAQUMT
drop table FAASTYPE
drop table FABLDG
drop table FACAPT
drop table FACNTL
drop table FACLASS
drop table FACMNTS
drop table FADEPT
drop table FADSPMT
drop table FAEQUP
drop table FAHIST
drop table FAMSTR
drop table FANEW
drop table FAUSER1
drop table FAUSER2
drop table FAUSER3
drop table MFPARK
drop table MFPCAT
drop table MFPRKH
drop table MFTCLS
drop table MFTRAN
drop table MFTPTYP
drop table MFTRNH
drop table MFTTYPE
drop table PKCNTL
drop table PKOFCR
drop table PKTICK
drop table PKVIOL
drop table PRCHK
drop table PRCHKD
drop table PRSUP
drop table PRSUPD
drop table PRGLMAP
