drop view ap1099l1
drop view apctrll1
drop view apehstl0
drop view apehstl1
drop view apehstl2
drop view apehstl3
drop view apehstl4
drop view apehstl5
drop view apehstl6
drop view apehstl7
drop view apehstl8
drop view apehstl9
drop view apehstla
drop view apeopnl1
drop view apeopnl2
drop view apeopnl3
drop view bchhdrl1
drop view bchhdrl9
drop view execjbl1
drop view execjbl2
drop view execjbl3
drop view famstrl1
drop view famstrl2
drop view glacctl1
drop view glacctl2
drop view glacctl7
drop view glacctl8
drop view glacctl9
drop view glebchl1
drop view glfundl1
drop view glfundl9
drop view ledgerl1
drop view ledgerl2
drop view ledgerl3
drop view ledgerl4
drop view ledgerl5
drop view ledgerl6
drop view ledgerl7
drop view ledgerl9
drop view ledhstl2
drop view msbilll1
drop view mvbilll1
drop view pomastl1
drop view pomastl2
drop view pomastl3
drop view pomastl4
drop view pomastl5
drop view pomastl6
drop view pomastl7
drop view pomastl8
drop view pomastl9
drop view pomastla
drop view pomhstl1
drop view pomhstl2
drop view ppbilll1
drop view purctll1
drop view rebilll1
drop view rpbilll1
drop view userx
drop view usery
drop view userz
drop view vendorl9