drop table ACCNARL
drop table APEBCH
drop table APEBCD
drop table APEBNC
drop table APEBNK
drop table APEHST
drop table APEOPN
drop table APERCN
drop table APCTRL
drop table AP1099P
drop table ARCUST
drop table BUDNAR
drop table CSHBCH
drop table DEPNARL
drop table DEPSEC
drop table FNDSEC
drop table GLACCT
drop table GLBUDGET
drop table GLDEP
drop table GLDEPGRP
drop table GLEBCH
drop table GLEDOBJ
drop table GLEDSUM
drop table GLFUND
drop table GLGRUP
drop table GLHEAD
drop table GLOBJT
drop table GLPROG
drop table GLRBCH
drop table GLSUBF
drop table GLTYPE
drop table LEDGER
drop table LEDHST
drop table LOCATN
drop table LOCSEC
drop table NETGLBCH
drop table POMAST
drop table POMEMO
drop table POMBCH
drop table POMBCD
drop table POSUMF
drop table PURCTL
drop table RQEBCH
drop table RQEBCD
drop table VENCAT
drop table VENDOR
drop table W2PRINT