alter table GNET add primary key (CODE)
alter table GNETGROUP add primary key (GGROUP)
alter table GNETSEC add primary key (GRPID, PGMID)
alter table GNETUSER add primary key (GUSER)
alter table GNETPGM add primary key (PGMID)
alter table TXCOEA add primary key (CCNO)
alter table TXCODE add primary key (TCCODE, TCTYPE)
alter table TXINV add primary key (LIST#, TYPE, YEAR)
alter table TXINVO add primary key (LIST#, TYPE, YEAR)
alter table TXPROF add primary key (PRTYPE, PRYEAR, PHS, DIST)
alter table TXSTS add primary key (STCODE)
alter table TXSUPCD add primary key (SCOD)