<?xml version="1.0" encoding="utf-8" ?> 
<xs:schema id="UB413Tot" 
                  targetNamespace="http://tempuri.org/UB413Tot.xsd"
                  elementFormDefault="qualified"
                  xmlns="http://tempuri.org/UB413Tot.xsd"
                  xmlns:mstns="http://tempuri.org/UB413Tot.xsd"
                  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="mytabletot">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="TYPE" type="xs:string" />
        <xs:element name="TORIGBAL" type="xs:decimal" />
        <xs:element name="TPAYMENTS" type="xs:decimal" />
        <xs:element name="TCURRBAL" type="xs:decimal" />
        <xs:element name="TUNBILLED" type="xs:decimal" />
        <xs:element name="TPRINBAL" type="xs:decimal" />
        <xs:element name="TENDBAL" type="xs:decimal" />
        <xs:element name="TINTEREST" type="xs:decimal" />
        <xs:element name="TLIEN" type="xs:decimal" />
        <xs:element name="TBOND" type="xs:decimal" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
