<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="AP502B" targetNamespace="http://tempuri.org/AP502B.xsd" elementFormDefault="qualified" xmlns="http://tempuri.org/AP502B.xsd" xmlns:mstns="http://tempuri.org/AP502B.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="mytable">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ACCT" type="xs:string" />
        <xs:element name="DESC" type="xs:string" />
        <xs:element name="ACTYP" type="xs:string" />
        <xs:element name="TRTYP" type="xs:string" />
       	<xs:element name="DAMOUNT" type="xs:decimal" />
        <xs:element name="CAMOUNT" type="xs:decimal" />
        <xs:element name="ERRORFOUND" type="xs:string" />
      </xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>