<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="TAP02Sum" 
  targetNamespace="http://tempuri.org/TAP02Sum.xsd"
  elementFormDefault="qualified" 
  xmlns="http://tempuri.org/TAP02Sum.xsd"
  xmlns:mstns="http://tempuri.org/TAP02Sum.xsd"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="mytable">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="listno" type="xs:integer" />
        <xs:element name="name" type="xs:string" />
				<xs:element name="laddr" type="xs:string" />
				<xs:element name="deyear" type="xs:integer" />
				<xs:element name="decost" type="xs:integer" />
        <xs:element name="pct" type="xs:integer" />
        <xs:element name="denet" type="xs:integer" />
        <xs:element name="ascost" type="xs:integer" />
        <xs:element name="asnet" type="xs:integer" />
      </xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>
