<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="TA4072" targetNamespace="http://tempuri.org/TA4072.xsd" elementFormDefault="qualified"
  xmlns="http://tempuri.org/TA4072.xsd" xmlns:mstns="http://tempuri.org/TA4072.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="mytable">
<xs:complexType>
<xs:sequence>
<xs:element name="LISTNO" type="xs:integer" />
<xs:element name="VALUE70" type="xs:integer" />
<xs:element name="LSTYRVAL" type="xs:integer" /> 
<xs:element name="LNVALUE" type="xs:integer" />
<xs:element name="TRADEIN" type="xs:integer" />
<xs:element name="MSRP" type="xs:integer" />
<xs:element name="ECODE" type="xs:string" />
<xs:element name="CLASS" type="xs:integer" />
<xs:element name="MAKE" type="xs:string" />
<xs:element name="YEAR" type="xs:integer" />
<xs:element name="IDNO" type="xs:string" />
<xs:element name="MODEL" type="xs:string" />
<xs:element name="BODY" type="xs:string" />
<xs:element name="CYL" type="xs:integer" />
<xs:element name="REGNO" type="xs:string" />
<xs:element name="ADDR1" type="xs:string" />
<xs:element name="ADDR2" type="xs:string" />
<xs:element name="ADDR3" type="xs:string" />
<xs:element name="ADDR4" type="xs:string" />
<xs:element name="ADDR5" type="xs:string" />
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>