<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="TA213Tot" targetNamespace="http://tempuri.org/TA213Tot.xsd" elementFormDefault="qualified" xmlns="http://tempuri.org/TA213Tot.xsd" xmlns:mstns="http://tempuri.org/TA213Tot.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="mytabletot">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="totletter" type="xs:string" />
        <xs:element name="totcount" type="xs:long" />
        <xs:element name="totgross" type="xs:long" />
        <xs:element name="totprorate" type="xs:long" />
        <xs:element name="totcreditgross" type="xs:long" />
        <xs:element name="totcredit" type="xs:long" />
        <xs:element name="totexam" type="xs:long" />
        <xs:element name="totnet" type="xs:long" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>