<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="TA518" targetNamespace="http://tempuri.org/TA518.xsd" elementFormDefault="qualified"
  xmlns="http://tempuri.org/TA518.xsd" xmlns:mstns="http://tempuri.org/TA518.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="mytable">
<xs:complexType>
<xs:sequence>
<xs:element name="LISTNO" type="xs:integer" />
<xs:element name="NAME" type="xs:string" />
<xs:element name="MAKE" type="xs:string" />
<xs:element name="YEAR" type="xs:integer" />
<xs:element name="MODEL" type="xs:string" />
<xs:element name="REGNO" type="xs:string" />
<xs:element name="CLASS" type="xs:integer" />
<xs:element name="OMAKE" type="xs:string" />
<xs:element name="OYEAR" type="xs:integer" />
<xs:element name="OMOD" type="xs:string" />
<xs:element name="OREG" type="xs:string" />
<xs:element name="OVIN" type="xs:string" />
<xs:element name="OLIST" type="xs:integer" />
<xs:element name="OASS" type="xs:string" />
<xs:element name="OVAL" type="xs:integer" />
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>