Imports System.Text
Module ProcessShared

Public Function HeadingsCSV(ByVal WrkAll As Boolean) As String
  Dim sb As StringBuilder
  Dim WrkComma As String

  WrkComma = ","
  sb = New StringBuilder
  sb.Append("CATEGORY")
  sb.Append(WrkComma)
  sb.Append("LIST NO")
  sb.Append(WrkComma)
  sb.Append("NAME")
  sb.Append(WrkComma)
  sb.Append("SECOND NAME")
  sb.Append(WrkComma)
  sb.Append("ADDRESS 1")
  sb.Append(WrkComma)
  sb.Append("ADDRESS 2")
  sb.Append(WrkComma)
  sb.Append("CITY")
  sb.Append(WrkComma)
  sb.Append("STATE")
  sb.Append(WrkComma)
  sb.Append("ZIP CODE")
  sb.Append(WrkComma)
  sb.Append("ZIP 4")
  sb.Append(WrkComma)
  sb.Append("LOCATION #")
  sb.Append(WrkComma)
  sb.Append("LOCATION NAME")
  sb.Append(WrkComma)
  sb.Append("GROSS ASSESSMENT")
  sb.Append(WrkComma)
  sb.Append("NET ASSESSMENT")
  sb.Append(WrkComma)
  sb.Append("ASSESSMENT 1")
  sb.Append(WrkComma)
  sb.Append("ASSESSMENT 2")
  sb.Append(WrkComma)
  sb.Append("ASSESSMENT 3")
  sb.Append(WrkComma)
  sb.Append("ASSESSMENT 4")
  sb.Append(WrkComma)
  sb.Append("ASSESSMENT 5")
  sb.Append(WrkComma)
  sb.Append("ASSESSMENT 6")
  sb.Append(WrkComma)
  sb.Append("ASSESSMENT 7")
  sb.Append(WrkComma)
  sb.Append("ASSESSMENT 8")
  sb.Append(WrkComma)
  sb.Append("ASSESSMENT 9")
  sb.Append(WrkComma)
  sb.Append("ASSESSMENT 10")
  sb.Append(WrkComma)
  sb.Append("PROPERTY CODE 1")
  sb.Append(WrkComma)
  sb.Append("PROPERTY CODE 2")
  sb.Append(WrkComma)
  sb.Append("PROPERTY CODE 3")
  sb.Append(WrkComma)
  sb.Append("PROPERTY CODE 4")
  sb.Append(WrkComma)
  sb.Append("PROPERTY CODE 5")
  sb.Append(WrkComma)
  sb.Append("PROPERTY CODE 6")
  sb.Append(WrkComma)
  sb.Append("PROPERTY CODE 7")
  sb.Append(WrkComma)
  sb.Append("PROPERTY CODE 8")
  sb.Append(WrkComma)
  sb.Append("PROPERTY CODE 9")
  sb.Append(WrkComma)
  sb.Append("PROPERTY CODE 10")
  sb.Append(WrkComma)
  sb.Append("UNIT 1")
  sb.Append(WrkComma)
  sb.Append("UNIT 2")
  sb.Append(WrkComma)
  sb.Append("UNIT 3")
  sb.Append(WrkComma)
  sb.Append("UNIT 4")
  sb.Append(WrkComma)
  sb.Append("UNIT 5")
  sb.Append(WrkComma)
  sb.Append("UNIT 6")
  sb.Append(WrkComma)
  sb.Append("UNIT 7")
  sb.Append(WrkComma)
  sb.Append("UNIT 8")
  sb.Append(WrkComma)
  sb.Append("UNIT 9")
  sb.Append(WrkComma)
  sb.Append("UNIT 10")
  sb.Append(WrkComma)
  sb.Append("DISTRICT")
  sb.Append(WrkComma)
  sb.Append("EXEMPTION CODE 1")
  sb.Append(WrkComma)
  sb.Append("EXEMPTION CODE 2")
  sb.Append(WrkComma)
  sb.Append("EXEMPTION CODE 3")
  sb.Append(WrkComma)
  sb.Append("EXEMPTION CODE 4")
  sb.Append(WrkComma)
  sb.Append("EXEMPTION CODE 5")
  sb.Append(WrkComma)
  sb.Append("EXEMPTION AMOUNT 1")
  sb.Append(WrkComma)
  sb.Append("EXEMPTION AMOUNT 2")
  sb.Append(WrkComma)
  sb.Append("EXEMPTION AMOUNT 3")
  sb.Append(WrkComma)
  sb.Append("EXEMPTION AMOUNT 4")
  sb.Append(WrkComma)
  sb.Append("EXEMPTION AMOUNT 5")
  sb.Append(WrkComma)
  sb.Append("BUSINESS TYPE CODE")
  sb.Append(WrkComma)
  sb.Append("SQ FT")
  sb.Append(WrkComma)
  sb.Append("AUDIT YEAR")
  'Rest of fields in file
  If WrkAll Then
    sb.Append(WrkComma)
    sb.Append("BACK TAX")
    sb.Append(WrkComma)
    sb.Append("BTR")
    sb.Append(WrkComma)
    sb.Append("BUSINESS?")
    sb.Append(WrkComma)
    sb.Append("C/C ASSESSMENT 1")
    sb.Append(WrkComma)
    sb.Append("C/C ASSESSMENT 2")
    sb.Append(WrkComma)
    sb.Append("C/C ASSESSMENT 3")
    sb.Append(WrkComma)
    sb.Append("C/C ASSESSMENT 4")
    sb.Append(WrkComma)
    sb.Append("C/C ASSESSMENT 5")
    sb.Append(WrkComma)
    sb.Append("C/C ASSESSMENT 6")
    sb.Append(WrkComma)
    sb.Append("C/C ASSESSMENT 7")
    sb.Append(WrkComma)
    sb.Append("C/C ASSESSMENT 8")
    sb.Append(WrkComma)
    sb.Append("C/C ASSESSMENT 9")
    sb.Append(WrkComma)
    sb.Append("C/C ASSESSMENT 10")
    sb.Append(WrkComma)
    sb.Append("C/C CODE 1")
    sb.Append(WrkComma)
    sb.Append("C/C CODE 2")
    sb.Append(WrkComma)
    sb.Append("C/C CODE 3")
    sb.Append(WrkComma)
    sb.Append("C/C CODE 4")
    sb.Append(WrkComma)
    sb.Append("C/C CODE 5")
    sb.Append(WrkComma)
    sb.Append("C/C EXEMPTION")
    sb.Append(WrkComma)
    sb.Append("C/C GROSS")
    sb.Append(WrkComma)
    sb.Append("C/C NO")
    sb.Append(WrkComma)
    sb.Append("C/C REASON")
    sb.Append(WrkComma)
    sb.Append("C/C DATE")
    sb.Append(WrkComma)
    sb.Append("C/C EXEMPTION AMOUNT 1")
    sb.Append(WrkComma)
    sb.Append("C/C EXEMPTION AMOUNT 2")
    sb.Append(WrkComma)
    sb.Append("C/C EXEMPTION AMOUNT 3")
    sb.Append(WrkComma)
    sb.Append("C/C EXEMPTION AMOUNT 4")
    sb.Append(WrkComma)
    sb.Append("C/C EXEMPTION AMOUNT 5")
    sb.Append(WrkComma)
    sb.Append("CHANGE DATE")
    sb.Append(WrkComma)
    sb.Append("CHANGE TIME")
    sb.Append(WrkComma)
    sb.Append("BTR DENIED?")
    sb.Append(WrkComma)
    sb.Append("BTR DATE")
    sb.Append(WrkComma)
    sb.Append("LETTER")
    sb.Append(WrkComma)
    sb.Append("OWNER ID")
    sb.Append(WrkComma)
    sb.Append("USERID")
    sb.Append(WrkComma)
    sb.Append("RENEWAL DATE")
    sb.Append(WrkComma)
    sb.Append("SS NO")
    sb.Append(WrkComma)
    sb.Append("SS NO 2")
    sb.Append(WrkComma)
    sb.Append("TIN")
    sb.Append(WrkComma)
    sb.Append("TAX TYPE")
  End If
  sb.Append(WrkComma)
  sb.Append("DECL YEAR")
  sb.Append(WrkComma)
  sb.Append("DECL FILING STATUS")
  sb.Append(WrkComma)
  sb.Append("DECL STATUS")
  sb.Append(WrkComma)
  sb.Append("BUSINESS TYPE DESCRIPTION")
  sb.Append(WrkComma)
  sb.Append("DECL EMAIL")
  sb.Append(WrkComma)
  sb.Append("DECL PHONE")
  sb.Append(WrkComma)
  sb.Append("DECL DATE RECIEVED")
  sb.Append(WrkComma)
  sb.Append("DECL DATE BUSINESS STARTED")
  sb.Append(WrkComma)
  sb.Append("DECL SQ FEET")
  sb.Append(WrkComma)
  sb.Append("DECL EMPLOYEES")
  Return sb.ToString
End Function
End Module






