update txinv set LIEN=''
FROM         TXHST INNER JOIN
                      TXINV ON TXHST.LIST# = TXINV.LIST# AND TXHST.YEAR = TXINV.YEAR AND TXHST.TYPE = TXINV.TYPE
WHERE     (txhst.rcode = 'I') AND (TXHST.PDATE = 20120611) AND (TXHST.BATCHA = 'L')and PDATE=20120611