<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="UB207Lbl"
                  targetNamespace="http://tempuri.org/UB207Lbl.xsd"
                  elementFormDefault="qualified"
                  xmlns="http://tempuri.org/UB207Lbl.xsd"
                  xmlns:mstns="http://tempuri.org/UB207Lbl.xsd"
                  xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="mytable">
      <xs:complexType>
        <xs:sequence>
          <xs:element name="line0" type="xs:string" />
          <xs:element name="line1" type="xs:string" />
          <xs:element name="line2" type="xs:string" />
          <xs:element name="line3" type="xs:string" />
          <xs:element name="line4" type="xs:string" />
          <xs:element name="line5" type="xs:string" />
        </xs:sequence>
      </xs:complexType>
    </xs:element>
  </xs:schema>
