<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="TXE10" targetNamespace="http://tempuri.org/TXE10.xsd" elementFormDefault="qualified"
  xmlns="http://tempuri.org/TXE10.xsd" xmlns:mstns="http://tempuri.org/TXE10.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="mytable">
<xs:complexType>
<xs:sequence>
<xs:element name="LISTNO" type="xs:integer" />
<xs:element name="YEAR" type="xs:integer" />
<xs:element name="TYPE" type="xs:string" />
<xs:element name="NAME" type="xs:string" />
<xs:element name="ADD1" type="xs:string" />
<xs:element name="ADD2" type="xs:string" />
<xs:element name="CITY" type="xs:string" />
<xs:element name="STATE" type="xs:string" />
<xs:element name="ZIP" type="xs:string" />
<xs:element name="PROPDESC" type="xs:string" />
<xs:element name="STATUS" type="xs:string" />
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>