<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="UB410Bill" targetNamespace="http://tempuri.org/UB410Bill.xsd" elementFormDefault="qualified" xmlns="http://tempuri.org/UB410Bill.xsd" xmlns:mstns="http://tempuri.org/UB410Bill.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="mytable2">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="LISTNO" type="xs:integer" />
				<xs:element name="YEAR" type="xs:integer" />
				<xs:element name="BILLTYPE" type="xs:string" />
				<xs:element name="ADDR1" type="xs:string" />
				<xs:element name="ADDR2" type="xs:string" />
				<xs:element name="ADDR3" type="xs:string" />
				<xs:element name="ADDR4" type="xs:string" />
				<xs:element name="ADDR5" type="xs:string" />
				<xs:element name="UNITS" type="xs:decimal" />
        <xs:element name="EDUS" type="xs:integer" />
        <xs:element name="CURRREAD" type="xs:integer" />
        <xs:element name="PREVREAD" type="xs:integer" />
        <xs:element name="USAGE" type="xs:integer" />
				<xs:element name="RATECODEA" type="xs:string" />
        <xs:element name="RATECODEA2" type="xs:string" />
        <xs:element name="RATECODEA3" type="xs:string" />
        <xs:element name="TAXTOT" type="xs:decimal" />
				<xs:element name="TAX1ST" type="xs:decimal" />
				<xs:element name="TAX2ND" type="xs:decimal" />
				<xs:element name="BILLAMTA" type="xs:decimal" />
				<xs:element name="BALANCEA" type="xs:decimal" />
				<xs:element name="INTERESTA" type="xs:decimal" />
				<xs:element name="LIENA" type="xs:decimal" />
        <xs:element name="RATECODEB" type="xs:string" />
        <xs:element name="RATECODEB2" type="xs:string" />
        <xs:element name="RATECODEB3" type="xs:string" />
        <xs:element name="BILLAMTB" type="xs:decimal" />
        <xs:element name="BALANCEB" type="xs:decimal" />
        <xs:element name="INTERESTB" type="xs:decimal" />
        <xs:element name="LIENB" type="xs:decimal" />
        <xs:element name="PROPDESC" type="xs:string" />
				<xs:element name="MAPBLOCK" type="xs:string" />
        <xs:element name="DUEDT1" type="xs:date" />
				<xs:element name="DUEDT2" type="xs:date" />
				<xs:element name="BACKTAX" type="xs:boolean" />
				<xs:element name="BARCODE" type="xs:string" />
				<xs:element name="ACCTIDA" type="xs:string" />
        <xs:element name="ACCTIDB" type="xs:string" />
        <xs:element name="ROUTE" type="xs:string" />
        <xs:element name="METERNO" type="xs:string" />
      </xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>