<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="GLA02Dtl"
    targetNamespace="http://tempuri.org/GLA02Dtl.xsd"
    elementFormDefault="qualified" 
    xmlns="http://tempuri.org/GLA02Dtl.xsd" 
    xmlns:mstns="http://tempuri.org/GLA02Dtl.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="mytable">
		<xs:complexType>
			<xs:sequence>
        <xs:element name="BCHNO" type="xs:integer" />
        <xs:element name="TAXBCHNO" type="xs:integer" />
        <xs:element name="SEQNO" type="xs:integer" />
        <xs:element name="DIST" type="xs:integer" />
				<xs:element name="CODE" type="xs:string" />
				<xs:element name="AMOUNT" type="xs:decimal" />
        <xs:element name="TYPE" type="xs:string" />
        <xs:element name="YEAR" type="xs:integer" />
        <xs:element name="SUSP" type="xs:string" />
        <xs:element name="ACCT" type="xs:string" />
      </xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

