<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="AP201" targetNamespace="http://tempuri.org/AP201.xsd" elementFormDefault="qualified"
  xmlns="http://tempuri.org/AP201.xsd" xmlns:mstns="http://tempuri.org/AP201.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="mytable">
<xs:complexType>
<xs:sequence>
<xs:element name="BCHNO" type="xs:integer" />
<xs:element name="SEQNO" type="xs:integer" />
<xs:element name="BCHDATE" type="xs:date" />
<xs:element name="VSORT" type="xs:string" />
<xs:element name="VENDOR" type="xs:string" />
<xs:element name="VENDNAME" type="xs:string" />
<xs:element name="VADD1" type="xs:string" />
<xs:element name="VADD2" type="xs:string" />
<xs:element name="VADD3" type="xs:string" />
<xs:element name="INVNO" type="xs:string" />
<xs:element name="INVAMT" type="xs:decimal" />
<xs:element name="INVDATE" type="xs:date" />
<xs:element name="DUEDATE" type="xs:date" />
<xs:element name="PONBR" type="xs:integer" />
<xs:element name="DESCR" type="xs:string" />
<xs:element name="ACCT" type="xs:string" />
<xs:element name="ACCTDESC" type="xs:string" />
<xs:element name="AMOUNT" type="xs:decimal" />
<xs:element name="PARTIAL" type="xs:string" />
<xs:element name="ERRMSG" type="xs:string" />
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>