<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="TXE16" targetNamespace="http://tempuri.org/TXE16.xsd" elementFormDefault="qualified"
  xmlns="http://tempuri.org/TXE16.xsd" xmlns:mstns="http://tempuri.org/TXE16.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="mytable">
<xs:complexType>
<xs:sequence>
  <xs:element name="LISTNO" type="xs:integer" />
  <xs:element name="YEAR" type="xs:integer" />
  <xs:element name="TYPE" type="xs:string" />
  <xs:element name="NAME" type="xs:string" />
  <xs:element name="ORIGINT" type="xs:decimal" />
  <xs:element name="INTPAID" type="xs:decimal" />
  <xs:element name="DATEPAID" type="xs:date" />
  <xs:element name="COMMENT" type="xs:string" />
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>