<?xml version="1.0" encoding="utf-8" ?>
<xs:schema id="TA523" targetNamespace="http://tempuri.org/TA523.xsd" elementFormDefault="qualified"
  xmlns="http://tempuri.org/TA523.xsd" xmlns:mstns="http://tempuri.org/TA523.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="mytable">
<xs:complexType>
<xs:sequence>
<xs:element name="LISTNO" type="xs:integer" />
<xs:element name="ONAME" type="xs:string" />
<xs:element name="CLASS" type="xs:integer" />
<xs:element name="MAKE" type="xs:string" />
<xs:element name="YEAR" type="xs:integer" />
<xs:element name="IDNO" type="xs:string" />
<xs:element name="MODEL" type="xs:string" />
<xs:element name="SOURCE" type="xs:string" />
<xs:element name="MSRP" type="xs:integer" />
<xs:element name="VALUE" type="xs:integer" />
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>